#!/bin/bash -l

cat <<EOH > /app/config/couchdb.yml
production:
  host: $COUCHDB_PORT_5984_TCP_ADDR
  port: $COUCHDB_PORT_5984_TCP_PORT
  https_port: $COUCHDB_PORT_6984_TCP_PORT
  prefix: primero
  suffix: ''
  username: primero
  password: $COUCHDB_PASSWORD
EOH

cat <<EOH > /app/config/sunspot.yml
production:
  solr:
    hostname: $SOLR_PORT_8983_TCP_ADDR
    port: $SOLR_PORT_8983_TCP_PORT
    log_level: INFO
    pid_dir: tmp/pids
    path: /solr/production
EOH

sed -e "s/<SERVER_NAME>/${PRIMERO_VIRTUAL_HOST}/" /etc/nginx/primero-template > /etc/nginx/sites-enabled/primero

if [ ! -e /app/.is_setup ]
then
  set -e
  bundle exec rake db:seed
  bundle exec rake db:migrate
  bundle exec rake couch_changes:prime_sequence_numbers

  bundle exec rake sunspot:solr:start
  bundle exec rake sunspot:reindex
  bundle exec rake sunspot:solr:stop
  touch /app/.is_setup
fi

exec "$@"
