#!/bin/bash

cat <<EOH > /app/config/couchdb.yml
production:
  host: $COUCHDB_PORT_5984_TCP_ADDR
  port: $COUCHDB_PORT_5984_TCP_PORT
  https_port: $COUCHDB_PORT_6984_TCP_PORT
  prefix: primero
  suffix:
  username: primero
  password: $COUCHDB_PASSWORD
EOH

cat <<EOH > /app/config/sunspot.yml
production:
  solr:
    hostname: $SOLR_PORT_8983_TCP_ADDR
    port: $SOLR_PORT_8983_TCP_PORT
    log_level: INFO
    pid_dir: tmp/pids
    path: /solr/production
EOH

if [ ! -f /app/.is_setup ]
then
  bundle exec rake db:seed
  bundle exec rake db:migrate
  bundle exec rake sunspot:reindex
  bundle exec rake couch_changes:prime_sequence_numbers
  touch /app/.is_setup
fi

exec "$@"
