import { namespaceActions } from "../../../../libs";
import NAMESPACE from "../namespace";

export default namespaceActions(NAMESPACE, [
  "CLEAR_METADATA",
  "USERS",
  "USERS_FINISHED",
  "USERS_STARTED",
  "USERS_SUCCESS",
  "SET_USERS_FILTER",
  "DISABLE_USERS",
  "DISABLE_USERS_STARTED",
  "DISABLE_USERS_SUCCESS",
  "DISABLE_USERS_FAILURE",
  "DISABLE_USERS_FINISHED",
  "SEND_EMAILS",
  "SEND_EMAILS_STARTED",
  "SEND_EMAILS_SUCCESS",
  "SEND_EMAILS_FAILURE",
  "SEND_EMAILS_FINISHED"
]);
