export const DASHBOARD_FLAGS = "DASHBOARD_FLAGS";
export const CASES_BY_CASE_WORKER = "CASES_BY_CASE_WORKER";
export const CASES_BY_STATUS = "CASES_BY_STATUS";
export const CASES_REGISTRATION = "CASES_REGISTRATION";
export const CASES_OVERVIEW = "CASES_OVERVIEW";
export const OPEN_PAGE_ACTIONS = "OPEN_PAGE_ACTIONS";
export const SERVICES_STATUS = "SERVICES_STATUS";
