// Copyright (c) 2014 - 2023 UNICEF. All rights reserved.

export { default } from "./component";

export { default as usePermissions } from "./use-permissions";

export {
  ACTIONS,
  ACTIVITY_LOGS,
  ADD_INCIDENT,
  ADD_NOTE,
  ADD_SERVICE,
  ADMIN_ACTIONS,
  ADMIN_RESOURCES,
  APPROVAL,
  ASSIGN,
  CONSENT_OVERRIDE,
  COPY_ROLES,
  CREATE_CASE_FROM_FAMILY,
  CREATE_INCIDENT,
  CREATE_RECORDS,
  CREATE_REPORTS,
  DASH_APPROVALS_PENDING,
  DASH_APPROVALS,
  DISPLAY_VIEW_PAGE,
  ENABLE_DISABLE_RECORD,
  EXPORT_CUSTOM,
  EXPORTS_PERMISSIONS,
  FLAG_RECORDS,
  GROUP_PERMISSIONS,
  LINK_FAMILY_RECORD_FROM_CASE,
  MANAGE,
  READ_MANAGED_REPORTS,
  READ_RECORDS,
  READ_REGISTRY_RECORD,
  READ_REPORTS,
  RECORD_RESOURCES,
  REFER_FROM_SERVICE,
  REQUEST_APPROVAL,
  FLAG_RESOLVE_ANY,
  RESOURCES,
  SHOW_APPROVALS,
  SHOW_AUDIT_LOGS,
  SHOW_CHANGE_LOG,
  SHOW_EXPORTS,
  SHOW_FIND_MATCH,
  SHOW_SUMMARY,
  SHOW_SYNC_EXTERNAL,
  SHOW_TASKS,
  VIEW_FAMILY_RECORD_FROM_CASE,
  VIEW_INCIDENTS_FROM_CASE,
  VIEW_KPIS,
  WRITE_RECORDS,
  WRITE_REGISTRY_RECORD,
  REMOVE_ALERT,
  SHOW_USAGE_REPORTS
} from "./constants";

export { checkPermissions } from "./utils";

export { getPermissionsByRecord } from "./selectors";
