import { namespaceActions } from "../../../../libs";

import NAMESPACE from "./namespace";

export default namespaceActions(NAMESPACE, [
  "RECORD_FORMS",
  "RECORD_FORMS_FAILURE",
  "RECORD_FORMS_FINISHED",
  "RECORD_FORMS_STARTED",
  "RECORD_FORMS_SUCCESS",
  "REORDER_FORM_GROUPS",
  "REORDER_FORM_SECTIONS",
  "SAVE_FORM_ORDER",
  "SAVE_FORM_ORDER_STARTED",
  "SAVE_FORM_ORDER_SUCCESS",
  "SAVE_FORM_ORDER_FAILURE",
  "SAVE_FORM_ORDER_FINISHED",
  "SET_REORDERED_FORMS"
]);
