export const FETCH_INSIGHTS = "reports/FETCH_INSIGHTS";
export const FETCH_INSIGHTS_STARTED = "reports/FETCH_INSIGHTS_STARTED";
export const FETCH_INSIGHTS_SUCCESS = "reports/FETCH_INSIGHTS_SUCCESS";
export const FETCH_INSIGHTS_FINISHED = "reports/FETCH_INSIGHTS_FINISHED";
export const FETCH_INSIGHTS_FAILURE = "reports/FETCH_INSIGHTS_FAILURE";
export const CLEAR_METADATA = "reports/CLEAR_METADATA";
