#Country
Location.create! placename: "Liberia", type: "country"

#county
Location.create! placename:"Grand Kru", type: "county", hierarchy: ["Liberia"]
Location.create! placename:"River Gee", type: "county", hierarchy: ["Liberia"]
Location.create! placename:"Grand Gedeh", type: "county", hierarchy: ["Liberia"]
Location.create! placename:"Rivercess", type: "county", hierarchy: ["Liberia"]
Location.create! placename:"Sinoe", type: "county", hierarchy: ["Liberia"]
Location.create! placename:"Nimba", type: "county", hierarchy: ["Liberia"]
Location.create! placename:"Gbarpolu", type: "county", hierarchy: ["Liberia"]
Location.create! placename:"Bong", type: "county", hierarchy: ["Liberia"]
Location.create! placename:"Montserrado", type: "county", hierarchy: ["Liberia"]
Location.create! placename:"Grand Bassa", type: "county", hierarchy: ["Liberia"]
Location.create! placename:"Bomi", type: "county", hierarchy: ["Liberia"]
Location.create! placename:"Margibi", type: "county", hierarchy: ["Liberia"]
Location.create! placename:"Lofa", type: "county", hierarchy: ["Liberia"]
Location.create! placename:"Grand Cape Mount", type: "county", hierarchy: ["Liberia"]
Location.create! placename:"Maryland", type: "county", hierarchy: ["Liberia"]

#district
Location.create! placename:"Dweh", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Gee", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Nyenawliken", type: "district", hierarchy: ["Liberia", "River Gee"]
Location.create! placename:"B'hai", type: "district", hierarchy: ["Liberia", "Grand Gedeh"]
Location.create! placename:"Fen River", type: "district", hierarchy: ["Liberia", "Rivercess"]
Location.create! placename:"Fenetoe", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Bodae", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Boe & Quilla", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Chedepo", type: "district", hierarchy: ["Liberia", "River Gee"]
Location.create! placename:"Barclayville", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Beawor", type: "district", hierarchy: ["Liberia", "Rivercess"]
Location.create! placename:"Belleh", type: "district", hierarchy: ["Liberia", "Gbarpolu"]
Location.create! placename:"Bleebo", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Boinsen", type: "district", hierarchy: ["Liberia", "Bong"]
Location.create! placename:"Bokomu", type: "district", hierarchy: ["Liberia", "Gbarpolu"]
Location.create! placename:"Felo-Jekwi", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Bokon", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Bolloh", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Bopolu", type: "district", hierarchy: ["Liberia", "Gbarpolu"]
Location.create! placename:"Commonwealth1", type: "district", hierarchy: ["Liberia", "Montserrado"]
Location.create! placename:"Buah", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Commonwealth2", type: "district", hierarchy: ["Liberia", "Grand Bassa"]
Location.create! placename:"District # 1", type: "district", hierarchy: ["Liberia", "Grand Bassa"]
Location.create! placename:"District # 2", type: "district", hierarchy: ["Liberia", "Grand Bassa"]
Location.create! placename:"District # 3", type: "district", hierarchy: ["Liberia", "Grand Bassa"]
Location.create! placename:"District # 4", type: "district", hierarchy: ["Liberia", "Grand Bassa"]
Location.create! placename:"Butaw", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Buu-Yao", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Careysburg", type: "district", hierarchy: ["Liberia", "Montserrado"]
Location.create! placename:"Doe", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Cavala", type: "district", hierarchy: ["Liberia", "Grand Gedeh"]
Location.create! placename:"Central Rivercess", type: "district", hierarchy: ["Liberia", "Rivercess"]
Location.create! placename:"Doedain", type: "district", hierarchy: ["Liberia", "Rivercess"]
Location.create! placename:"Dorbor", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Dowein", type: "district", hierarchy: ["Liberia", "Bomi"]
Location.create! placename:"Dugbe River", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Fuamah", type: "district", hierarchy: ["Liberia", "Bong"]
Location.create! placename:"Gbao", type: "district", hierarchy: ["Liberia", "Grand Gedeh"]
Location.create! placename:"Firestone", type: "district", hierarchy: ["Liberia", "Margibi"]
Location.create! placename:"Forpoh", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Foya", type: "district", hierarchy: ["Liberia", "Lofa"]
Location.create! placename:"Garr-Bain", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Garraway", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Gbeapo", type: "district", hierarchy: ["Liberia", "River Gee"]
Location.create! placename:"Garwula", type: "district", hierarchy: ["Liberia", "Grand Cape Mount"]
Location.create! placename:"Gbehlay-Geh", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Gbarma", type: "district", hierarchy: ["Liberia", "Gbarpolu"]
Location.create! placename:"Glaro", type: "district", hierarchy: ["Liberia", "River Gee"]
Location.create! placename:"Gbi & Doru", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Gboe-Ploe", type: "district", hierarchy: ["Liberia", "Grand Gedeh"]
Location.create! placename:"Gbor", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Glio-Twarbo", type: "district", hierarchy: ["Liberia", "Grand Gedeh"]
Location.create! placename:"Golakonneh", type: "district", hierarchy: ["Liberia", "Grand Cape Mount"]
Location.create! placename:"Gounwolaila", type: "district", hierarchy: ["Liberia", "Gbarpolu"]
Location.create! placename:"Gwelekpoken", type: "district", hierarchy: ["Liberia", "Maryland"]
Location.create! placename:"Grand Cess Wedabo", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Greenville", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Jorquelleh", type: "district", hierarchy: ["Liberia", "Bong"]
Location.create! placename:"Harper", type: "district", hierarchy: ["Liberia", "Maryland"]
Location.create! placename:"Karforh", type: "district", hierarchy: ["Liberia", "River Gee"]
Location.create! placename:"Jaedae", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Jeadepo", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Jo River", type: "district", hierarchy: ["Liberia", "Rivercess"]
Location.create! placename:"Putu", type: "district", hierarchy: ["Liberia", "Grand Gedeh"]
Location.create! placename:"Juarzon", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Karluway#2", type: "district", hierarchy: ["Liberia", "Maryland"]
Location.create! placename:"Karluway#1", type: "district", hierarchy: ["Liberia", "Maryland"]
Location.create! placename:"Potupo", type: "district", hierarchy: ["Liberia", "River Gee"]
Location.create! placename:"Kokoyah", type: "district", hierarchy: ["Liberia", "Bong"]
Location.create! placename:"Kpi", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Klay", type: "district", hierarchy: ["Liberia", "Bomi"]
Location.create! placename:"Kolahun", type: "district", hierarchy: ["Liberia", "Lofa"]
Location.create! placename:"Kongba", type: "district", hierarchy: ["Liberia", "Gbarpolu"]
Location.create! placename:"Konobo", type: "district", hierarchy: ["Liberia", "Grand Gedeh"]
Location.create! placename:"Kpaai", type: "district", hierarchy: ["Liberia", "Bong"]
Location.create! placename:"Kparblee", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Kpayan", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Lower Jloh", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Mambah Kaba", type: "district", hierarchy: ["Liberia", "Margibi"]
Location.create! placename:"Kulu Shaw Boe", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Leewehpea-Mahn", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Meinpea-Mahn", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Nanee", type: "district", hierarchy: ["Liberia", "River Gee"]
Location.create! placename:"Neekreen", type: "district", hierarchy: ["Liberia", "Grand Bassa"]
Location.create! placename:"Norwein", type: "district", hierarchy: ["Liberia", "Rivercess"]
Location.create! placename:"Nrokwia-Wesldow", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Nyenebo", type: "district", hierarchy: ["Liberia", "River Gee"]
Location.create! placename:"Nyorken", type: "district", hierarchy: ["Liberia", "Maryland"]
Location.create! placename:"Owensgrove", type: "district", hierarchy: ["Liberia", "Grand Bassa"]
Location.create! placename:"Panta", type: "district", hierarchy: ["Liberia", "Bong"]
Location.create! placename:"Plahn Nyarn", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Pleebo/Sodoken", type: "district", hierarchy: ["Liberia", "Maryland"]
Location.create! placename:"Porkpa", type: "district", hierarchy: ["Liberia", "Grand Cape Mount"]
Location.create! placename:"Pynes Town", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Quardu Boundi", type: "district", hierarchy: ["Liberia", "Lofa"]
Location.create! placename:"Salayea", type: "district", hierarchy: ["Liberia", "Lofa"]
Location.create! placename:"Sam Gbalor", type: "district", hierarchy: ["Liberia", "Rivercess"]
Location.create! placename:"Sanniquellie Mahn", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Sanquin Dist# 3", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Sanoyeah", type: "district", hierarchy: ["Liberia", "Bong"]
Location.create! placename:"Sanquin Dist# 1", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Sanquin Dist#2", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Sarbo", type: "district", hierarchy: ["Liberia", "River Gee"]
Location.create! placename:"Yarmein", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Seekon", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Yarpea Mahn", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Senjeh", type: "district", hierarchy: ["Liberia", "Bomi"]
Location.create! placename:"St. John River City", type: "district", hierarchy: ["Liberia", "Grand Bassa"]
Location.create! placename:"Zoe-Gbao", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"St. Paul River", type: "district", hierarchy: ["Liberia", "Montserrado"]
Location.create! placename:"Suakoko", type: "district", hierarchy: ["Liberia", "Bong"]
Location.create! placename:"Tchien", type: "district", hierarchy: ["Liberia", "Grand Gedeh"]
Location.create! placename:"Suehn Mecca", type: "district", hierarchy: ["Liberia", "Bomi"]
Location.create! placename:"Tuobo", type: "district", hierarchy: ["Liberia", "River Gee"]
Location.create! placename:"Tewor", type: "district", hierarchy: ["Liberia", "Grand Cape Mount"]
Location.create! placename:"Vahun", type: "district", hierarchy: ["Liberia", "Lofa"]
Location.create! placename:"Todee", type: "district", hierarchy: ["Liberia", "Montserrado"]
Location.create! placename:"Trenbo", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Tukpahblee", type: "district", hierarchy: ["Liberia", "Bong"]
Location.create! placename:"Twan River", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Upper Jloh", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Voinjama", type: "district", hierarchy: ["Liberia", "Lofa"]
Location.create! placename:"Whojah", type: "district", hierarchy: ["Liberia", "Maryland"]
Location.create! placename:"Wlogba", type: "district", hierarchy: ["Liberia", "Grand Kru"]
Location.create! placename:"Wedjah", type: "district", hierarchy: ["Liberia", "Sinoe"]
Location.create! placename:"Wee-Gbehyi-Mahn", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Yarwein Mehnsonnoh", type: "district", hierarchy: ["Liberia", "Nimba"]
Location.create! placename:"Zorzor", type: "district", hierarchy: ["Liberia", "Lofa"]
Location.create! placename:"Yeallequelleh", type: "district", hierarchy: ["Liberia", "Bong"]
Location.create! placename:"Zarflahn", type: "district", hierarchy: ["Liberia", "Rivercess"]
Location.create! placename:"Zota", type: "district", hierarchy: ["Liberia", "Bong"]
Location.create! placename:"Gibi", type: "district", hierarchy: ["Liberia", "Margibi"]
Location.create! placename:"Greater Monrovia", type: "district", hierarchy: ["Liberia", "Montserrado"]
Location.create! placename:"Kakata", type: "district", hierarchy: ["Liberia", "Margibi"]
Location.create! placename:"Salala", type: "district", hierarchy: ["Liberia", "Bong"]
Location.create! placename:"Commonwealth", type: "district", hierarchy: ["Liberia", "Grand Cape Mount"]
