#Country
Location.create! placename: "Sierra Leone", admin_level: 0, location_code:"SLE", type: "country"

#province
Location.create! placename:"Southern", location_code:"SLE03", type: "province", hierarchy: ["SLE"]
Location.create! placename:"Northern", location_code:"SLE02", type: "province", hierarchy: ["SLE"]
Location.create! placename:"Eastern", location_code:"SLE01", type: "province", hierarchy: ["SLE"]
Location.create! placename:"Western Area", location_code:"SLE04", type: "province", hierarchy: ["SLE"]

#district
Location.create! placename:"Bo", location_code:"SLE0301", type: "district", hierarchy: ["SLE", "SLE03"]
Location.create! placename:"Pujehun", location_code:"SLE0304", type: "district", hierarchy: ["SLE", "SLE03"]
Location.create! placename:"Bombali", location_code:"SLE0201", type: "district", hierarchy: ["SLE", "SLE02"]
Location.create! placename:"Bonthe", location_code:"SLE0302", type: "district", hierarchy: ["SLE", "SLE03"]
Location.create! placename:"Kailahun", location_code:"SLE0101", type: "district", hierarchy: ["SLE", "SLE01"]
Location.create! placename:"Kambia", location_code:"SLE0202", type: "district", hierarchy: ["SLE", "SLE02"]
Location.create! placename:"Kenema", location_code:"SLE0102", type: "district", hierarchy: ["SLE", "SLE01"]
Location.create! placename:"Kono", location_code:"SLE0103", type: "district", hierarchy: ["SLE", "SLE01"]
Location.create! placename:"Koinadugu", location_code:"SLE0203", type: "district", hierarchy: ["SLE", "SLE02"]
Location.create! placename:"Moyamba", location_code:"SLE0303", type: "district", hierarchy: ["SLE", "SLE03"]
Location.create! placename:"Port Loko", location_code:"SLE0204", type: "district", hierarchy: ["SLE", "SLE02"]
Location.create! placename:"Tonkolili", location_code:"SLE0205", type: "district", hierarchy: ["SLE", "SLE02"]
Location.create! placename:"Western Area Urban (Freetown)", location_code:"SLE0402", type: "district", hierarchy: ["SLE", "SLE04"]
Location.create! placename:"Western Area Rural", location_code:"SLE0401", type: "district", hierarchy: ["SLE", "SLE04"]

#chiefdom
Location.create! placename:"Badjia", location_code:"SLE030101", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Bagbo", location_code:"SLE030102", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Jaiama Bongor", location_code:"SLE030107", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Kakua", location_code:"SLE030108", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Bagbwe(Bagbe)", location_code:"SLE030103", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Gbo", location_code:"SLE030106", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Bo Town", location_code:"SLE030191", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Boama", location_code:"SLE030104", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Komboya", location_code:"SLE030109", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Bumpe Ngao", location_code:"SLE030105", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Lugbu", location_code:"SLE030110", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Sowa", location_code:"SLE030411", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0304"]
Location.create! placename:"Niawa Lenga", location_code:"SLE030111", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Selenga", location_code:"SLE030112", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Tikonko", location_code:"SLE030113", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Valunia", location_code:"SLE030114", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Wonde", location_code:"SLE030115", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0301"]
Location.create! placename:"Biriwa", location_code:"SLE020101", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0201"]
Location.create! placename:"Gbanti Kamarank", location_code:"SLE020103", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0201"]
Location.create! placename:"Bombali Sebora", location_code:"SLE020102", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0201"]
Location.create! placename:"Gbendembu Ngowa", location_code:"SLE020104", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0201"]
Location.create! placename:"Libeisaygahun", location_code:"SLE020105", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0201"]
Location.create! placename:"Magbaimba Ndorh", location_code:"SLE020106", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0201"]
Location.create! placename:"Makari Gbanti", location_code:"SLE020107", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0201"]
Location.create! placename:"Bendu-Cha", location_code:"SLE030201", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0302"]
Location.create! placename:"Paki Masabong", location_code:"SLE020108", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0201"]
Location.create! placename:"Kpanda Kemo", location_code:"SLE030206", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0302"]
Location.create! placename:"Safroko Limba", location_code:"SLE020109", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0201"]
Location.create! placename:"Sanda Loko", location_code:"SLE020110", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0201"]
Location.create! placename:"Kwamebai Krim", location_code:"SLE030207", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0302"]
Location.create! placename:"Sanda Tendaran", location_code:"SLE020111", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0201"]
Location.create! placename:"Sella Limba", location_code:"SLE020112", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0201"]
Location.create! placename:"Tambakha", location_code:"SLE020113", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0201"]
Location.create! placename:"Bonthe Urban", location_code:"SLE030291", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0302"]
Location.create! placename:"Bum", location_code:"SLE030202", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0302"]
Location.create! placename:"Dema", location_code:"SLE030203", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0302"]
Location.create! placename:"Imperri", location_code:"SLE030204", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0302"]
Location.create! placename:"Jong", location_code:"SLE030205", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0302"]
Location.create! placename:"Nongoba Bullom", location_code:"SLE030208", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0302"]
Location.create! placename:"Sittia", location_code:"SLE030209", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0302"]
Location.create! placename:"Sogbeni", location_code:"SLE030210", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0302"]
Location.create! placename:"Yawbeko", location_code:"SLE030211", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0302"]
Location.create! placename:"Dea", location_code:"SLE010101", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0101"]
Location.create! placename:"Jawie", location_code:"SLE010102", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0101"]
Location.create! placename:"Kissi Kama", location_code:"SLE010103", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0101"]
Location.create! placename:"Kissi Teng", location_code:"SLE010104", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0101"]
Location.create! placename:"Kpeje Bongre", location_code:"SLE010106", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0101"]
Location.create! placename:"Kissi Tongi", location_code:"SLE010105", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0101"]
Location.create! placename:"Kpeje West", location_code:"SLE010107", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0101"]
Location.create! placename:"Luawa", location_code:"SLE010108", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0101"]
Location.create! placename:"Malema", location_code:"SLE010109", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0101"]
Location.create! placename:"Mandu", location_code:"SLE010110", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0101"]
Location.create! placename:"Njaluahun", location_code:"SLE010111", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0101"]
Location.create! placename:"Penguia", location_code:"SLE010112", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0101"]
Location.create! placename:"Upper Bambara", location_code:"SLE010113", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0101"]
Location.create! placename:"Yawei", location_code:"SLE010114", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0101"]
Location.create! placename:"Bramaia", location_code:"SLE020201", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0202"]
Location.create! placename:"Gbinle Dixing", location_code:"SLE020202", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0202"]
Location.create! placename:"Masungbala", location_code:"SLE020205", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0202"]
Location.create! placename:"Samu", location_code:"SLE020206", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0202"]
Location.create! placename:"Magbema", location_code:"SLE020203", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0202"]
Location.create! placename:"Mambolo", location_code:"SLE020204", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0202"]
Location.create! placename:"Tonko Limba", location_code:"SLE020207", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0202"]
Location.create! placename:"Dama", location_code:"SLE010201", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Gorama Mende", location_code:"SLE010204", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Dodo", location_code:"SLE010202", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Gaura", location_code:"SLE010203", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Kandu Leppiama", location_code:"SLE010205", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Niawa", location_code:"SLE010210", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Kenema Town", location_code:"SLE010291", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Koya", location_code:"SLE010206", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Langrama", location_code:"SLE010207", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Lower Bambara", location_code:"SLE010208", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Malegohun", location_code:"SLE010209", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Nomo", location_code:"SLE010211", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Nongowa", location_code:"SLE010212", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Simbaru", location_code:"SLE010213", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Koidu Town", location_code:"SLE010391", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0103"]
Location.create! placename:"Small Bo", location_code:"SLE010214", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Tunkia", location_code:"SLE010215", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Wandor", location_code:"SLE010216", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0102"]
Location.create! placename:"Dembelia - Sink", location_code:"SLE020301", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0203"]
Location.create! placename:"Folosaba Dembel", location_code:"SLE020303", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0203"]
Location.create! placename:"Diang", location_code:"SLE020302", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0203"]
Location.create! placename:"Kasunko", location_code:"SLE020304", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0203"]
Location.create! placename:"Mongo", location_code:"SLE020305", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0203"]
Location.create! placename:"Neya", location_code:"SLE020306", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0203"]
Location.create! placename:"Nieni", location_code:"SLE020307", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0203"]
Location.create! placename:"Sengbe", location_code:"SLE020308", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0203"]
Location.create! placename:"Sulima", location_code:"SLE020309", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0203"]
Location.create! placename:"Wara Wara Bafod", location_code:"SLE020310", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0203"]
Location.create! placename:"Fiama", location_code:"SLE010301", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0103"]
Location.create! placename:"Wara Wara Yagal", location_code:"SLE020311", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0203"]
Location.create! placename:"Mafindor", location_code:"SLE010308", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0103"]
Location.create! placename:"Gbane", location_code:"SLE010302", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0103"]
Location.create! placename:"Gbane Kandor", location_code:"SLE010303", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0103"]
Location.create! placename:"Gbense", location_code:"SLE010304", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0103"]
Location.create! placename:"Gorama Kono", location_code:"SLE010305", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0103"]
Location.create! placename:"Kamara", location_code:"SLE010306", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0103"]
Location.create! placename:"Lei", location_code:"SLE010307", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0103"]
Location.create! placename:"Nimikoro", location_code:"SLE010309", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0103"]
Location.create! placename:"Nimiyama", location_code:"SLE010310", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0103"]
Location.create! placename:"Sandor", location_code:"SLE010311", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0103"]
Location.create! placename:"Soa", location_code:"SLE010312", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0103"]
Location.create! placename:"Upper Banta", location_code:"SLE030314", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0303"]
Location.create! placename:"Tankoro", location_code:"SLE010313", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0103"]
Location.create! placename:"Toli", location_code:"SLE010314", type: "chiefdom", hierarchy: ["SLE", "SLE01", "SLE0103"]
Location.create! placename:"Makeni Town", location_code:"SLE020191", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0201"]
Location.create! placename:"Bagruwa", location_code:"SLE030301", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0303"]
Location.create! placename:"Bumpeh", location_code:"SLE030302", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0303"]
Location.create! placename:"Dasse", location_code:"SLE030303", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0303"]
Location.create! placename:"Fakunya", location_code:"SLE030304", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0303"]
Location.create! placename:"Kagboro", location_code:"SLE030305", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0303"]
Location.create! placename:"Kaiyamba", location_code:"SLE030306", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0303"]
Location.create! placename:"Kamajei", location_code:"SLE030307", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0303"]
Location.create! placename:"Kongbora", location_code:"SLE030308", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0303"]
Location.create! placename:"Kori", location_code:"SLE030309", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0303"]
Location.create! placename:"Kowa", location_code:"SLE030310", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0303"]
Location.create! placename:"Lower Banta", location_code:"SLE030311", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0303"]
Location.create! placename:"Ribbi", location_code:"SLE030312", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0303"]
Location.create! placename:"Buya Romende", location_code:"SLE020402", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0204"]
Location.create! placename:"Timdale", location_code:"SLE030313", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0303"]
Location.create! placename:"Bureh Kasseh Ma", location_code:"SLE020401", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0204"]
Location.create! placename:"Dibia", location_code:"SLE020403", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0204"]
Location.create! placename:"Kaffu Bullom", location_code:"SLE020404", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0204"]
Location.create! placename:"Lokomasama", location_code:"SLE020406", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0204"]
Location.create! placename:"Maforki", location_code:"SLE020407", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0204"]
Location.create! placename:"Marampa", location_code:"SLE020408", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0204"]
Location.create! placename:"Masimera", location_code:"SLE020409", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0204"]
Location.create! placename:"Sanda Magbolont", location_code:"SLE020410", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0204"]
Location.create! placename:"TMS", location_code:"SLE020411", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0204"]
Location.create! placename:"Barri", location_code:"SLE030401", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0304"]
Location.create! placename:"Mono Sakrim", location_code:"SLE030407", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0304"]
Location.create! placename:"Galliness Perri", location_code:"SLE030402", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0304"]
Location.create! placename:"Panga Kabonde", location_code:"SLE030404", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0304"]
Location.create! placename:"Kpaka", location_code:"SLE030403", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0304"]
Location.create! placename:"Makpele", location_code:"SLE030405", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0304"]
Location.create! placename:"Malen", location_code:"SLE030406", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0304"]
Location.create! placename:"Panga krim", location_code:"SLE030408", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0304"]
Location.create! placename:"Pejeh(Futa peje", location_code:"SLE030409", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0304"]
Location.create! placename:"Soro Gbema", location_code:"SLE030410", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0304"]
Location.create! placename:"Yakemu Kpukumu", location_code:"SLE030412", type: "chiefdom", hierarchy: ["SLE", "SLE03", "SLE0304"]
Location.create! placename:"Gbonkolenken", location_code:"SLE020501", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0205"]
Location.create! placename:"Kafe Simiria", location_code:"SLE020502", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0205"]
Location.create! placename:"East I", location_code:"SLE040203", type: "chiefdom", hierarchy: ["SLE", "SLE04", "SLE0402"]
Location.create! placename:"Kalansogoia", location_code:"SLE020503", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0205"]
Location.create! placename:"Kholifa Mabang", location_code:"SLE020504", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0205"]
Location.create! placename:"Kholifa Rowala", location_code:"SLE020505", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0205"]
Location.create! placename:"Kunike", location_code:"SLE020507", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0205"]
Location.create! placename:"Kunike Barina", location_code:"SLE020506", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0205"]
Location.create! placename:"Malal Mara", location_code:"SLE020508", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0205"]
Location.create! placename:"Sambaya", location_code:"SLE020509", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0205"]
Location.create! placename:"Tane", location_code:"SLE020510", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0205"]
Location.create! placename:"Yoni", location_code:"SLE020511", type: "chiefdom", hierarchy: ["SLE", "SLE02", "SLE0205"]
Location.create! placename:"Koya Rural", location_code:"SLE040101", type: "chiefdom", hierarchy: ["SLE", "SLE04", "SLE0401"]
Location.create! placename:"Mountain Rural", location_code:"SLE040102", type: "chiefdom", hierarchy: ["SLE", "SLE04", "SLE0401"]
Location.create! placename:"Waterloo Rural", location_code:"SLE040103", type: "chiefdom", hierarchy: ["SLE", "SLE04", "SLE0401"]
Location.create! placename:"York Rural", location_code:"SLE040104", type: "chiefdom", hierarchy: ["SLE", "SLE04", "SLE0401"]
Location.create! placename:"Central I", location_code:"SLE040201", type: "chiefdom", hierarchy: ["SLE", "SLE04", "SLE0402"]
Location.create! placename:"Central II", location_code:"SLE040202", type: "chiefdom", hierarchy: ["SLE", "SLE04", "SLE0402"]
Location.create! placename:"East II", location_code:"SLE040204", type: "chiefdom", hierarchy: ["SLE", "SLE04", "SLE0402"]
Location.create! placename:"East III", location_code:"SLE040205", type: "chiefdom", hierarchy: ["SLE", "SLE04", "SLE0402"]
Location.create! placename:"West I", location_code:"SLE040206", type: "chiefdom", hierarchy: ["SLE", "SLE04", "SLE0402"]
Location.create! placename:"West II", location_code:"SLE040207", type: "chiefdom", hierarchy: ["SLE", "SLE04", "SLE0402"]
Location.create! placename:"West III", location_code:"SLE040208", type: "chiefdom", hierarchy: ["SLE", "SLE04", "SLE0402"]
