#Country
Location.create! placename: "Kenya", admin_level: 0, type: "country"

#Provinces
Location.create! placename: "Coast", type: "province", hierarchy: ["Kenya"]
Location.create! placename: "North Eastern", type: "province", hierarchy: ["Kenya"]
Location.create! placename: "Eastern", type: "province", hierarchy: ["Kenya"]
Location.create! placename: "Central", type: "province", hierarchy: ["Kenya"]
Location.create! placename: "Rift Valley", type: "province", hierarchy: ["Kenya"]
Location.create! placename: "Western", type: "province", hierarchy: ["Kenya"]
Location.create! placename: "Nyanza", type: "province", hierarchy: ["Kenya"]
Location.create! placename: "Nairobi", type: "province", hierarchy: ["Kenya"]

#Counties
Location.create! placename: "Mombasa", type: "county", hierarchy: ["Kenya", "Coast"]
Location.create! placename: "Kwale", type: "county", hierarchy: ["Kenya", "Coast"]
Location.create! placename: "Kilifi", type: "county", hierarchy: ["Kenya", "Coast"]
Location.create! placename: "Tana River", type: "county", hierarchy: ["Kenya", "Coast"]
Location.create! placename: "Lamu", type: "county", hierarchy: ["Kenya", "Coast"]
Location.create! placename: "Taita-Taveta", type: "county", hierarchy: ["Kenya", "Coast"]
Location.create! placename: "Garissa", type: "county", hierarchy: ["Kenya", "North Eastern"]
Location.create! placename: "Wajir", type: "county", hierarchy: ["Kenya", "North Eastern"]
Location.create! placename: "Mandera", type: "county", hierarchy: ["Kenya", "North Eastern"]
Location.create! placename: "Marsabit", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! placename: "Isiolo", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! placename: "Meru", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! placename: "Tharaka-Nithi", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! placename: "Embu", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! placename: "Kitui", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! placename: "Machakos", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! placename: "Makueni", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! placename: "Nyandarua", type: "county", hierarchy: ["Kenya", "Central"]
Location.create! placename: "Nyeri", type: "county", hierarchy: ["Kenya", "Central"]
Location.create! placename: "Kirinyaga", type: "county", hierarchy: ["Kenya", "Central"]
Location.create! placename: "Murang'a", type: "county", hierarchy: ["Kenya", "Central"]
Location.create! placename: "Kiambu", type: "county", hierarchy: ["Kenya", "Central"]
Location.create! placename: "Turkana", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! placename: "West Pokot", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! placename: "Samburu", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! placename: "Trans Nzoia", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! placename: "Uasin Gishu", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! placename: "Elgeyo-Marakwet", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! placename: "Nandi", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! placename: "Baringo", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! placename: "Laikipia", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! placename: "Nakuru", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! placename: "Narok", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! placename: "Kajiado", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! placename: "Kericho", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! placename: "Bomet", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! placename: "Kakamega", type: "county", hierarchy: ["Kenya", "Western"]
Location.create! placename: "Vihiga", type: "county", hierarchy: ["Kenya", "Western"]
Location.create! placename: "Bungoma", type: "county", hierarchy: ["Kenya", "Western"]
Location.create! placename: "Busia", type: "county", hierarchy: ["Kenya", "Western"]
Location.create! placename: "Siaya", type: "county", hierarchy: ["Kenya", "Nyanza"]
Location.create! placename: "Kisumu", type: "county", hierarchy: ["Kenya", "Nyanza"]
Location.create! placename: "Homa Bay", type: "county", hierarchy: ["Kenya", "Nyanza"]
Location.create! placename: "Migori", type: "county", hierarchy: ["Kenya", "Nyanza"]
Location.create! placename: "Kisii", type: "county", hierarchy: ["Kenya", "Nyanza"]
Location.create! placename: "Nyamira", type: "county", hierarchy: ["Kenya", "Nyanza"]
Location.create! placename: "Nairobi", type: "county", hierarchy: ["Kenya", "Nairobi"]

#Cities
Location.create! placename: "Mombasa(City)", type: "city", hierarchy: ["Kenya", "Coast", "Mombasa"]
Location.create! placename: "Kwale", type: "city", hierarchy: ["Kenya", "Coast", "Kwale"]
Location.create! placename: "Kilifi", type: "city", hierarchy: ["Kenya", "Coast", "Kilifi"]
Location.create! placename: "Hola", type: "city", hierarchy: ["Kenya", "Coast", "Tana River"]
Location.create! placename: "Lamu", type: "city", hierarchy: ["Kenya", "Coast", "Lamu"]
Location.create! placename: "Voi", type: "city", hierarchy: ["Kenya", "Coast", "Taita-Taveta"]
Location.create! placename: "Garissa", type: "city", hierarchy: ["Kenya", "North Eastern", "Garissa"]
Location.create! placename: "Wajir", type: "city", hierarchy: ["Kenya", "North Eastern", "Wajir"]
Location.create! placename: "Mandera", type: "city", hierarchy: ["Kenya", "North Eastern", "Mandera"]
Location.create! placename: "Marsabit", type: "city", hierarchy: ["Kenya", "Eastern", "Marsabit"]
Location.create! placename: "Isiolo", type: "city", hierarchy: ["Kenya", "Eastern", "Isiolo"]
Location.create! placename: "Meru", type: "city", hierarchy: ["Kenya", "Eastern", "Meru"]
Location.create! placename: "Chuka", type: "city", hierarchy: ["Kenya", "Eastern", "Tharaka-Nithi"]
Location.create! placename: "Embu", type: "city", hierarchy: ["Kenya", "Eastern", "Embu"]
Location.create! placename: "Kitui", type: "city", hierarchy: ["Kenya", "Eastern", "Kitui"]
Location.create! placename: "Machakos", type: "city", hierarchy: ["Kenya", "Eastern", "Machakos"]
Location.create! placename: "Wote", type: "city", hierarchy: ["Kenya", "Eastern", "Makueni"]
Location.create! placename: "Ol Kalou", type: "city", hierarchy: ["Kenya", "Central", "Nyandarua"]
Location.create! placename: "Nyeri", type: "city", hierarchy: ["Kenya", "Central", "Nyeri"]
Location.create! placename: "Kerugoya/Kutus", type: "city", hierarchy: ["Kenya", "Central", "Kirinyaga"]
Location.create! placename: "Murang'a", type: "city", hierarchy: ["Kenya", "Central", "Murang'a"]
Location.create! placename: "Kiambu", type: "city", hierarchy: ["Kenya", "Central", "Kiambu"]
Location.create! placename: "Lodwar", type: "city", hierarchy: ["Kenya", "Rift Valley", "Turkana"]
Location.create! placename: "Kapenguria", type: "city", hierarchy: ["Kenya", "Rift Valley", "West Pokot"]
Location.create! placename: "Maralal", type: "city", hierarchy: ["Kenya", "Rift Valley", "Samburu"]
Location.create! placename: "Kitale", type: "city", hierarchy: ["Kenya", "Rift Valley", "Trans Nzoia"]
Location.create! placename: "Eldoret", type: "city", hierarchy: ["Kenya", "Rift Valley", "Uasin Gishu"]
Location.create! placename: "Iten", type: "city", hierarchy: ["Kenya", "Rift Valley", "Elgeyo-Marakwet"]
Location.create! placename: "Kapsabet", type: "city", hierarchy: ["Kenya", "Rift Valley", "Nandi"]
Location.create! placename: "Kabarnet", type: "city", hierarchy: ["Kenya", "Rift Valley", "Baringo"]
Location.create! placename: "Rumuruti", type: "city", hierarchy: ["Kenya", "Rift Valley", "Laikipia"]
Location.create! placename: "Nakuru", type: "city", hierarchy: ["Kenya", "Rift Valley", "Nakuru"]
Location.create! placename: "Narok", type: "city", hierarchy: ["Kenya", "Rift Valley", "Narok"]
Location.create! placename: "Kajiado", type: "city", hierarchy: ["Kenya", "Rift Valley", "Kajiado"]
Location.create! placename: "Kericho", type: "city", hierarchy: ["Kenya", "Rift Valley", "Kericho"]
Location.create! placename: "Bomet", type: "city", hierarchy: ["Kenya", "Rift Valley", "Bomet"]
Location.create! placename: "Kakamega", type: "city", hierarchy: ["Kenya", "Western", "Kakamega"]
Location.create! placename: "Vihiga", type: "city", hierarchy: ["Kenya", "Western", "Vihiga"]
Location.create! placename: "Bungoma", type: "city", hierarchy: ["Kenya", "Western", "Bungoma"]
Location.create! placename: "Busia", type: "city", hierarchy: ["Kenya", "Western", "Busia"]
Location.create! placename: "Siaya", type: "city", hierarchy: ["Kenya", "Nyanza", "Siaya"]
Location.create! placename: "Kisumu", type: "city", hierarchy: ["Kenya", "Nyanza", "Kisumu"]
Location.create! placename: "Homa Bay", type: "city", hierarchy: ["Kenya", "Nyanza", "Homa Bay"]
Location.create! placename: "Migori", type: "city", hierarchy: ["Kenya", "Nyanza", "Migori"]
Location.create! placename: "Kisii", type: "city", hierarchy: ["Kenya", "Nyanza", "Kisii"]
Location.create! placename: "Nyamira", type: "city", hierarchy: ["Kenya", "Nyanza", "Nyamira"]
Location.create! placename: "Nairobi(City)", type: "city", hierarchy: ["Kenya", "Nairobi", "Nairobi"]

#Camps
Location.create! placename: "Kakuma", type: "camp", hierarchy: ["Kenya", "Rift Valley", "Turkana"]
Location.create! placename: "Kakuma I", type: "camp", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma"]
Location.create! placename: "Zone 1", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma I"]
Location.create! placename: "Zone 2", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma I"]
Location.create! placename: "Zone 3", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma I"]
Location.create! placename: "Kakuma II", type: "camp", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma"]
Location.create! placename: "Zone 1", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma II"]
Location.create! placename: "Zone 2", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma II"]
Location.create! placename: "Kakuma III", type: "camp", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma"]
Location.create! placename: "Zone 1", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma III"]
Location.create! placename: "Zone 2", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma III"]
Location.create! placename: "Kakuma IV", type: "camp", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma"]
Location.create! placename: "Zone 1", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma IV"]

Location.create! placename: "Dadaab", type: "camp", hierarchy: ["Kenya", "North Eastern", "Garissa"]


