#Country
Location.create! placename: "Guinea", type: "country"

#region
Location.create! placename:"Kindia", type: "region", hierarchy: ["Kindia"]
Location.create! placename:"Nzerekore", type: "region", hierarchy: ["Nzerekore"]
Location.create! placename:"Labe", type: "region", hierarchy: ["Labe"]
Location.create! placename:"Mamou", type: "region", hierarchy: ["Mamou"]
Location.create! placename:"Faranah", type: "region", hierarchy: ["Faranah"]
Location.create! placename:"Conakry", type: "region", hierarchy: ["Conakry"]
Location.create! placename:"Kankan", type: "region", hierarchy: ["Kankan"]
Location.create! placename:"Boke", type: "region", hierarchy: ["Boke"]

#prefecture
Location.create! placename:"Coyah", type: "prefecture", hierarchy: ["Coyah", "Kindia"]
Location.create! placename:"Yomou", type: "prefecture", hierarchy: ["Yomou", "Nzerekore"]
Location.create! placename:"Lelouma", type: "prefecture", hierarchy: ["Lelouma", "Labe"]
Location.create! placename:"Nzerekore", type: "prefecture", hierarchy: ["Nzerekore", "Nzerekore"]
Location.create! placename:"Lola", type: "prefecture", hierarchy: ["Lola", "Nzerekore"]
Location.create! placename:"Mamou", type: "prefecture", hierarchy: ["Mamou", "Mamou"]
Location.create! placename:"Gueckedou", type: "prefecture", hierarchy: ["Gueckedou", "Nzerekore"]
Location.create! placename:"Macenta", type: "prefecture", hierarchy: ["Macenta", "Nzerekore"]
Location.create! placename:"Beyla", type: "prefecture", hierarchy: ["Beyla", "Nzerekore"]
Location.create! placename:"Kissidougou", type: "prefecture", hierarchy: ["Kissidougou", "Faranah"]
Location.create! placename:"Forecariah", type: "prefecture", hierarchy: ["Forecariah", "Kindia"]
Location.create! placename:"Conakry", type: "prefecture", hierarchy: ["Conakry", "Conakry"]
Location.create! placename:"Kerouane", type: "prefecture", hierarchy: ["Kerouane", "Kankan"]
Location.create! placename:"Dalaba", type: "prefecture", hierarchy: ["Dalaba", "Mamou"]
Location.create! placename:"Dubreka", type: "prefecture", hierarchy: ["Dubreka", "Kindia"]
Location.create! placename:"Pita", type: "prefecture", hierarchy: ["Pita", "Mamou"]
Location.create! placename:"Faranah", type: "prefecture", hierarchy: ["Faranah", "Faranah"]
Location.create! placename:"Boffa", type: "prefecture", hierarchy: ["Boffa", "Boke"]
Location.create! placename:"Fria", type: "prefecture", hierarchy: ["Fria", "Boke"]
Location.create! placename:"Boke", type: "prefecture", hierarchy: ["Boke", "Boke"]
Location.create! placename:"Kankan", type: "prefecture", hierarchy: ["Kankan", "Kankan"]
Location.create! placename:"Dabola", type: "prefecture", hierarchy: ["Dabola", "Faranah"]
Location.create! placename:"Labe", type: "prefecture", hierarchy: ["Labe", "Labe"]
Location.create! placename:"Kouroussa", type: "prefecture", hierarchy: ["Kouroussa", "Kankan"]
Location.create! placename:"Mandiana", type: "prefecture", hierarchy: ["Mandiana", "Kankan"]
Location.create! placename:"Tougue", type: "prefecture", hierarchy: ["Tougue", "Labe"]
Location.create! placename:"Koubia", type: "prefecture", hierarchy: ["Koubia", "Labe"]
Location.create! placename:"Dinguiraye", type: "prefecture", hierarchy: ["Dinguiraye", "Faranah"]
Location.create! placename:"Gaoual", type: "prefecture", hierarchy: ["Gaoual", "Boke"]
Location.create! placename:"Mali", type: "prefecture", hierarchy: ["Mali", "Labe"]
Location.create! placename:"Siguiri", type: "prefecture", hierarchy: ["Siguiri", "Kankan"]
Location.create! placename:"Koundara", type: "prefecture", hierarchy: ["Koundara", "Boke"]
Location.create! placename:"Kindia", type: "prefecture", hierarchy: ["Kindia", "Kindia"]
Location.create! placename:"Telimele", type: "prefecture", hierarchy: ["Telimele", "Kindia"]
