#Country
Location.create! name: "Kenya", type: "country"

#Provinces
Location.create! name: "Coast", type: "province", hierarchy: ["Kenya"]
Location.create! name: "North Eastern", type: "province", hierarchy: ["Kenya"]
Location.create! name: "Eastern", type: "province", hierarchy: ["Kenya"]
Location.create! name: "Central", type: "province", hierarchy: ["Kenya"]
Location.create! name: "Rift Valley", type: "province", hierarchy: ["Kenya"]
Location.create! name: "Western", type: "province", hierarchy: ["Kenya"]
Location.create! name: "Nyanza", type: "province", hierarchy: ["Kenya"]
Location.create! name: "Nairobi", type: "province", hierarchy: ["Kenya"]

#Counties
Location.create! name: "Mombasa", type: "county", hierarchy: ["Kenya", "Coast"]
Location.create! name: "Kwale", type: "county", hierarchy: ["Kenya", "Coast"]
Location.create! name: "Kilifi", type: "county", hierarchy: ["Kenya", "Coast"]
Location.create! name: "Tana River", type: "county", hierarchy: ["Kenya", "Coast"]
Location.create! name: "Lamu", type: "county", hierarchy: ["Kenya", "Coast"]
Location.create! name: "Taita-Taveta", type: "county", hierarchy: ["Kenya", "Coast"]
Location.create! name: "Garissa", type: "county", hierarchy: ["Kenya", "North Eastern"]
Location.create! name: "Wajir", type: "county", hierarchy: ["Kenya", "North Eastern"]
Location.create! name: "Mandera", type: "county", hierarchy: ["Kenya", "North Eastern"]
Location.create! name: "Marsabit", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! name: "Isiolo", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! name: "Meru", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! name: "Tharaka-Nithi", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! name: "Embu", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! name: "Kitui", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! name: "Machakos", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! name: "Makueni", type: "county", hierarchy: ["Kenya", "Eastern"]
Location.create! name: "Nyandarua", type: "county", hierarchy: ["Kenya", "Central"]
Location.create! name: "Nyeri", type: "county", hierarchy: ["Kenya", "Central"]
Location.create! name: "Kirinyaga", type: "county", hierarchy: ["Kenya", "Central"]
Location.create! name: "Murang'a", type: "county", hierarchy: ["Kenya", "Central"]
Location.create! name: "Kiambu", type: "county", hierarchy: ["Kenya", "Central"]
Location.create! name: "Turkana", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! name: "West Pokot", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! name: "Samburu", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! name: "Trans Nzoia", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! name: "Uasin Gishu", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! name: "Elgeyo-Marakwet", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! name: "Nandi", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! name: "Baringo", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! name: "Laikipia", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! name: "Nakuru", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! name: "Narok", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! name: "Kajiado", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! name: "Kericho", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! name: "Bomet", type: "county", hierarchy: ["Kenya", "Rift Valley"]
Location.create! name: "Kakamega", type: "county", hierarchy: ["Kenya", "Western"]
Location.create! name: "Vihiga", type: "county", hierarchy: ["Kenya", "Western"]
Location.create! name: "Bungoma", type: "county", hierarchy: ["Kenya", "Western"]
Location.create! name: "Busia", type: "county", hierarchy: ["Kenya", "Western"]
Location.create! name: "Siaya", type: "county", hierarchy: ["Kenya", "Nyanza"]
Location.create! name: "Kisumu", type: "county", hierarchy: ["Kenya", "Nyanza"]
Location.create! name: "Homa Bay", type: "county", hierarchy: ["Kenya", "Nyanza"]
Location.create! name: "Migori", type: "county", hierarchy: ["Kenya", "Nyanza"]
Location.create! name: "Kisii", type: "county", hierarchy: ["Kenya", "Nyanza"]
Location.create! name: "Nyamira", type: "county", hierarchy: ["Kenya", "Nyanza"]
Location.create! name: "Nairobi", type: "county", hierarchy: ["Kenya", "Nairobi"]

#Cities
Location.create! name: "Mombasa(City)", type: "city", hierarchy: ["Kenya", "Coast", "Mombasa"]
Location.create! name: "Kwale", type: "city", hierarchy: ["Kenya", "Coast", "Kwale"]
Location.create! name: "Kilifi", type: "city", hierarchy: ["Kenya", "Coast", "Kilifi"]
Location.create! name: "Hola", type: "city", hierarchy: ["Kenya", "Coast", "Tana River"]
Location.create! name: "Lamu", type: "city", hierarchy: ["Kenya", "Coast", "Lamu"]
Location.create! name: "Voi", type: "city", hierarchy: ["Kenya", "Coast", "Taita-Taveta"]
Location.create! name: "Garissa", type: "city", hierarchy: ["Kenya", "North Eastern", "Garissa"]
Location.create! name: "Wajir", type: "city", hierarchy: ["Kenya", "North Eastern", "Wajir"]
Location.create! name: "Mandera", type: "city", hierarchy: ["Kenya", "North Eastern", "Mandera"]
Location.create! name: "Marsabit", type: "city", hierarchy: ["Kenya", "Eastern", "Marsabit"]
Location.create! name: "Isiolo", type: "city", hierarchy: ["Kenya", "Eastern", "Isiolo"]
Location.create! name: "Meru", type: "city", hierarchy: ["Kenya", "Eastern", "Meru"]
Location.create! name: "Chuka", type: "city", hierarchy: ["Kenya", "Eastern", "Tharaka-Nithi"]
Location.create! name: "Embu", type: "city", hierarchy: ["Kenya", "Eastern", "Embu"]
Location.create! name: "Kitui", type: "city", hierarchy: ["Kenya", "Eastern", "Kitui"]
Location.create! name: "Machakos", type: "city", hierarchy: ["Kenya", "Eastern", "Machakos"]
Location.create! name: "Wote", type: "city", hierarchy: ["Kenya", "Eastern", "Makueni"]
Location.create! name: "Ol Kalou", type: "city", hierarchy: ["Kenya", "Central", "Nyandarua"]
Location.create! name: "Nyeri", type: "city", hierarchy: ["Kenya", "Central", "Nyeri"]
Location.create! name: "Kerugoya/Kutus", type: "city", hierarchy: ["Kenya", "Central", "Kirinyaga"]
Location.create! name: "Murang'a", type: "city", hierarchy: ["Kenya", "Central", "Murang'a"]
Location.create! name: "Kiambu", type: "city", hierarchy: ["Kenya", "Central", "Kiambu"]
Location.create! name: "Lodwar", type: "city", hierarchy: ["Kenya", "Rift Valley", "Turkana"]
Location.create! name: "Kapenguria", type: "city", hierarchy: ["Kenya", "Rift Valley", "West Pokot"]
Location.create! name: "Maralal", type: "city", hierarchy: ["Kenya", "Rift Valley", "Samburu"]
Location.create! name: "Kitale", type: "city", hierarchy: ["Kenya", "Rift Valley", "Trans Nzoia"]
Location.create! name: "Eldoret", type: "city", hierarchy: ["Kenya", "Rift Valley", "Uasin Gishu"]
Location.create! name: "Iten", type: "city", hierarchy: ["Kenya", "Rift Valley", "Elgeyo-Marakwet"]
Location.create! name: "Kapsabet", type: "city", hierarchy: ["Kenya", "Rift Valley", "Nandi"]
Location.create! name: "Kabarnet", type: "city", hierarchy: ["Kenya", "Rift Valley", "Baringo"]
Location.create! name: "Rumuruti", type: "city", hierarchy: ["Kenya", "Rift Valley", "Laikipia"]
Location.create! name: "Nakuru", type: "city", hierarchy: ["Kenya", "Rift Valley", "Nakuru"]
Location.create! name: "Narok", type: "city", hierarchy: ["Kenya", "Rift Valley", "Narok"]
Location.create! name: "Kajiado", type: "city", hierarchy: ["Kenya", "Rift Valley", "Kajiado"]
Location.create! name: "Kericho", type: "city", hierarchy: ["Kenya", "Rift Valley", "Kericho"]
Location.create! name: "Bomet", type: "city", hierarchy: ["Kenya", "Rift Valley", "Bomet"]
Location.create! name: "Kakamega", type: "city", hierarchy: ["Kenya", "Western", "Kakamega"]
Location.create! name: "Vihiga", type: "city", hierarchy: ["Kenya", "Western", "Vihiga"]
Location.create! name: "Bungoma", type: "city", hierarchy: ["Kenya", "Western", "Bungoma"]
Location.create! name: "Busia", type: "city", hierarchy: ["Kenya", "Western", "Busia"]
Location.create! name: "Siaya", type: "city", hierarchy: ["Kenya", "Nyanza", "Siaya"]
Location.create! name: "Kisumu", type: "city", hierarchy: ["Kenya", "Nyanza", "Kisumu"]
Location.create! name: "Homa Bay", type: "city", hierarchy: ["Kenya", "Nyanza", "Homa Bay"]
Location.create! name: "Migori", type: "city", hierarchy: ["Kenya", "Nyanza", "Migori"]
Location.create! name: "Kisii", type: "city", hierarchy: ["Kenya", "Nyanza", "Kisii"]
Location.create! name: "Nyamira", type: "city", hierarchy: ["Kenya", "Nyanza", "Nyamira"]
Location.create! name: "Nairobi(City)", type: "city", hierarchy: ["Kenya", "Nairobi", "Nairobi"]

#Camps
Location.create! name: "Kakuma", type: "camp", hierarchy: ["Kenya", "Rift Valley", "Turkana"]
Location.create! name: "Kakuma I", type: "camp", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma"]
Location.create! name: "Zone 1", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma I"]
Location.create! name: "Zone 2", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma I"]
Location.create! name: "Zone 3", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma I"]
Location.create! name: "Kakuma II", type: "camp", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma"]
Location.create! name: "Zone 1", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma II"]
Location.create! name: "Zone 2", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma II"]
Location.create! name: "Kakuma III", type: "camp", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma"]
Location.create! name: "Zone 1", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma III"]
Location.create! name: "Zone 2", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma III"]
Location.create! name: "Kakuma IV", type: "camp", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma"]
Location.create! name: "Zone 1", type: "zone", hierarchy: ["Kenya", "Rift Valley", "Turkana", "Kakuma", "Kakuma IV"]

Location.create! name: "Dadaab", type: "camp", hierarchy: ["Kenya", "North Eastern", "Garissa"]


