import NAMESPACE from "./namespace";

export const SET_AUTHENTICATED_USER = `${NAMESPACE}/SET_AUTHENTICATED_USER`;
export const FETCH_USER_DATA = `${NAMESPACE}/FETCH_USER_DATA`;
export const FETCH_USER_DATA_SUCCESS = `${NAMESPACE}/FETCH_USER_DATA_SUCCESS`;
export const LOGOUT = `${NAMESPACE}/LOGOUT`;
export const LOGOUT_STARTED = `${NAMESPACE}/LOGOUT_STARTED`;
export const LOGOUT_SUCCESS = `${NAMESPACE}/LOGOUT_SUCCESS`;
export const LOGOUT_FINISHED = `${NAMESPACE}/LOGOUT_FINISHED`;
export const LOGOUT_FAILURE = `${NAMESPACE}/LOGOUT_FAILURE`;
export const LOGOUT_SUCCESS_CALLBACK = `${NAMESPACE}/LOGOUT_SUCCESS_CALLBACK`;
