# frozen_string_literal: true

registry_details_fields = [
  Field.new(name: 'registry_id',
            type: 'text_field',
            editable: false,
            disabled: true,
            display_name_en: 'Long ID',
            mobile_visible: false,
            visible: false),
  Field.new(name: 'short_id',
            type: 'text_field',
            editable: false,
            disabled: true,
            display_name_en: 'Short ID',
            mobile_visible: false,
            visible: false),
  Field.new(name: 'registry_id_display',
            type: 'text_field',
            editable: false,
            disabled: true,
            display_name_en: 'Registry ID'),
  Field.new(name: 'status',
            type: 'select_box',
            selected_value: Record::STATUS_OPEN,
            display_name_en: 'Registry Status',
            option_strings_source: 'lookup lookup-registry-status',
            editable: false,
            disabled: true),
  Field.new(name: 'marked_for_mobile',
            type: 'tick_box',
            tick_box_label_en: 'Yes',
            display_name_en: 'Marked for mobile?',
            editable: false,
            disabled: true,
            mobile_visible: false,
            visible: false),
  Field.new(name: 'registration_date',
            type: 'date_field',
            selected_value: 'today',
            required: false,
            display_name_en: 'Registration Date',
            date_validation: 'not_future_date'),
  Field.new(name: 'registry_category',
            type: 'select_box',
            display_name_en: 'Registry Category',
            option_strings_source: 'lookup lookup-registry-category',
            visible: false),
  Field.new(name: 'name',
            type: 'text_field',
            display_name_en: 'Registry Name',
            hidden_text_field: true),
  Field.new(name: 'sex',
            type: 'select_box',
            show_on_minify_form: true,
            display_name_en: 'Sex',
            option_strings_source: 'lookup lookup-gender'),
  Field.new(name: 'registry_no',
            type: 'text_field',
            display_name_en: 'Registry ID Number'),
  Field.new(name: 'other_id_no_system',
            type: 'text_field',
            display_name_en: 'Other ID Number',
            visible: false),
  Field.new(name: 'address_current',
            type: 'textarea',
            display_name_en: 'Current Address'),
  Field.new(name: 'landmark_current',
            type: 'text_field',
            display_name_en: 'Landmark',
            visible: false),
  Field.new(name: 'location_current',
            type: 'select_box',
            display_name_en: 'Current Location',
            option_strings_source: 'Location'),
  Field.new(name: 'telephone_current',
            type: 'text_field',
            display_name_en: 'Current Telephone')
]

FormSection.create_or_update!(unique_id: 'registry_details',
                              parent_form: 'registry_record',
                              visible: false,
                              order_form_group: 10,
                              order: 10,
                              order_subform: 0,
                              form_group_id: 'registry_details',
                              fields: registry_details_fields,
                              is_first_tab: true,
                              editable: true,
                              name_en: 'Registry Details',
                              description_en: 'Registry Details')
