AllCops:
  Exclude:
    - db/schema.rb
    - tmp

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - Gemfile*
    - config/routes.rb
    - lib/tasks/*
    - spec/**/*

Metrics/ClassLength:
  Max: 125

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Exclude:
    - db/migrate/*
    - spec/**/*

Style/FrozenStringLiteralComment:
  Exclude:
    - bin/*

Style/OptionalBooleanParameter:
  Enabled: false
