import NAMESPACE from "./namespace";

export const FETCH_FLAGS = `${NAMESPACE}/FETCH_FLAGS`;
export const FETCH_FLAGS_SUCCESS = `${NAMESPACE}/FETCH_FLAGS_SUCCESS`;

export const UNFLAG = `${NAMESPACE}/UNFLAG`;
export const UNFLAG_SUCCESS = `${NAMESPACE}/UNFLAG_SUCCESS`;

export const ADD_FLAG = `${NAMESPACE}/ADD_FLAG`;
export const ADD_FLAG_SUCCESS = `${NAMESPACE}/ADD_FLAG_SUCCESS`;

export const SET_SELECTED_FLAG = `${NAMESPACE}/SET_SELECTED_FLAG`;
export const SET_SELECTED_FLAG_SUCCESS = `${NAMESPACE}/SET_SELECTED_FLAG_SUCCESS`;
