export const APPROVE_TRANSFER = "APPROVE_TRANSFER";
export const APPROVE_TRANSFER_STARTED = "APPROVE_TRANSFER_STARTED";
export const APPROVE_TRANSFER_SUCCESS = "APPROVE_TRANSFER_SUCCESS";
export const APPROVE_TRANSFER_FINISHED = "APPROVE_TRANSFER_FINISHED";
export const APPROVE_TRANSFER_FAILURE = "APPROVE_TRANSFER_FAILURE";