import NAMESPACE from "./namespace";

export const APPROVE_TRANSFER = `${NAMESPACE}/APPROVE_TRANSFER`;
export const APPROVE_TRANSFER_STARTED = `${NAMESPACE}/APPROVE_TRANSFER_STARTED`;
export const APPROVE_TRANSFER_SUCCESS = `${NAMESPACE}/APPROVE_TRANSFER_SUCCESS`;
export const APPROVE_TRANSFER_FINISHED = `${NAMESPACE}/APPROVE_TRANSFER_FINISHED`;
export const APPROVE_TRANSFER_FAILURE = `${NAMESPACE}/APPROVE_TRANSFER_FAILURE`;
