transitions_subform = [
    Field.new({"name" => "type",
               "type" => "select_box",
               "editable"=>false,
               "disabled" => true,
               "display_name_en" => "Type",
               "option_strings_source" => "lookup lookup-transition-type"
              }),
    Field.new({"name" => "to_user_local",
               "type" => "text_field",
               "editable"=>false,
               "disabled" => true,
               "display_name_en" => "Local User",
              }),
    Field.new({"name" => "to_user_remote",
               "type" => "text_field",
               "editable"=>false,
               "disabled" => true,
               "display_name_en" => "Remote User",
              }),
    Field.new({"name" => "to_user_local_status",
               "type" => "select_box",
               "editable" => false,
               "disabled" => true,
               "display_name_en" => "Status",
               "option_strings_text_en" => [
                 { id: 'in_progress', display_text: "In Progress" },
                 { id: 'pending', display_text: "Pending" },
                 { id: 'accepted', display_text: "Accepted" },
                 { id: 'rejected', display_text: "Rejected" },
                 { id: 'done', display_text: "Done" }
               ].map(&:with_indifferent_access)
              }),
    Field.new({"name" => "rejected_reason",
               "type" => "text_field",
               "editable"=>false,
               "disabled" => true,
               "display_name_en" => "Reason rejected (if applicable)",
              }),
    Field.new({"name" => "to_user_agency",
               "type" => "text_field",
               "editable"=>false,
               "disabled" => true,
               "display_name_en" => "Remote User Agency",
              }),
    Field.new({"name" => "notes",
               "type" => "textarea",
               "editable"=>false,
               "disabled" => true,
               "display_name_en" => "Notes",
              }),
    Field.new({"name" => "transitioned_by",
               "type" => "text_field",
               "editable"=>false,
               "disabled" => true,
               "display_name_en" => "Transferred or Referred By",
              }),
    Field.new({"name" => "service",
               "type" => "select_box",
               "editable"=>false,
               "disabled" => true,
               "display_name_en" => "Service",
               "option_strings_source" => "lookup lookup-service-type"
              }),
    Field.new({"name" => "is_remote",
               "type" => "tick_box",
               "tick_box_label_en" => "Yes",
               "editable"=>false,
               "disabled" => true,
               "display_name_en" => "Is the referral or transfer to a remote system?",
              }),
    Field.new({"name" => "type_of_export",
               "type" => "text_field",
               "editable"=>false,
               "disabled" => true,
               "display_name_en" => "What type of export do you want",
              }),
    Field.new({"name" => "consent_overridden",
               "type" => "tick_box",
               "tick_box_label_en" => "Yes",
               "editable"=>false,
               "disabled" => true,
               "display_name_en" => "No Consent to Share Setting Overridden",
              }),
    Field.new({"name" => "consent_individual_transfer",
               "type" => "tick_box",
               "tick_box_label_en" => "Yes",
               "editable" => false,
               "disabled" => true,
               "display_name_en" => "Did the case worker have the child's consent to make this transfer?"
              }),
    Field.new({"name" => "created_at",
               "type" => "date_field",
               "editable"=>false,
               "disabled" => true,
               "display_name_en" => "Date of referral or transfer",
               "date_include_time" => true
              }),
    Field.new({"name" => "service_section_unique_id",
               "type" => "text_field",
               "editable"=> false,
               "disabled" => true,
               "visible" => false,
               "mobile_visible" => false,
               "display_name_en" => "Service Form ID",
              }),
]

transitions = FormSection.create_or_update_form_section({
     "visible"=>false,
     "is_nested"=>true,
     :order_form_group => 150,
     :order => 10,
     :order_subform => 1,
     :unique_id=>"transitions",
     :parent_form=>"case",
     "editable"=>false,
     :fields => transitions_subform,
     "name_en" => "Nested Transitions Subform",
     "description_en" => "Transitions Subform",
     "collapsed_fields" => ["type", "service", "to_user_local", "to_user_remote", "created_at"]
})

referral_transfer_fields = [
  Field.new({"name" => "transfer_status",
             "type" => "select_box",
             "editable" => false,
             "disabled" => true,
             "display_name_en" => "Transfer Status",
             "option_strings_text_en" => [
               { id: 'in_progress', display_text: "In Progress" },
               { id: 'accepted', display_text: "Accepted" },
               { id: 'rejected', display_text: "Rejected" }
             ].map(&:with_indifferent_access)
            }),
  Field.new({"name" => "transitions",
             "type" => "subform",
             "editable" => false,
             "disabled" => true,
             "subform_section_id" => transitions.unique_id,
             "display_name_en" => "Transfers and Referrals",
             "subform_sort_by" => "created_at"
            })
]

FormSection.create_or_update_form_section({
  :unique_id=>"referral_transfer",
  :parent_form=>"case",
  "visible" => true,
  :order_form_group => 150,
  :order => 10,
  :order_subform => 0,
  :form_group_id => "referrals_transfers",
  "editable" => false,
  :fields => referral_transfer_fields,
  :is_first_tab => true,
  "name_en" => "Referrals and Transfers",
  "description_en" => "List of Transfers and Referrals"
})
