import { namespaceActions } from "../../../libs";

import NAMESPACE from "./namespace";

export default namespaceActions(NAMESPACE, [
  "FETCH_EXPORTS",
  "FETCH_EXPORTS_STARTED",
  "FETCH_EXPORTS_SUCCESS",
  "FETCH_EXPORTS_FINISHED",
  "FETCH_EXPORTS_FAILURE",
  "DELETE_EXPORT",
  "DELETE_EXPORT_STARTED",
  "DELETE_EXPORT_SUCCESS",
  "DELETE_EXPORT_FINISHED",
  "DELETE_EXPORT_FAILURE"
]);
