import NAMESPACE from "./namespace";

export const LOGIN = `${NAMESPACE}/LOGIN`;
export const LOGIN_STARTED = `${NAMESPACE}/LOGIN_STARTED`;
export const LOGIN_SUCCESS = `${NAMESPACE}/LOGIN_SUCCESS`;
export const LOGIN_FINISHED = `${NAMESPACE}/LOGIN_FINISHED`;
export const LOGIN_FAILURE = `${NAMESPACE}/LOGIN_FAILURE`;
export const LOGIN_SUCCESS_CALLBACK = `${NAMESPACE}/LOGIN_SUCCESS_CALLBACK`;
