export const FETCH_REPORTS = "reports/FETCH_REPORTS";
export const FETCH_REPORTS_STARTED = "reports/FETCH_REPORTS_STARTED";
export const FETCH_REPORTS_SUCCESS = "reports/FETCH_REPORTS_SUCCESS";
export const FETCH_REPORTS_FINISHED = "reports/FETCH_REPORTS_FINISHED";
export const FETCH_REPORTS_FAILURE = "reports/FETCH_REPORTS_FAILURE";
