export const ASSIGN_USERS_FETCH = "ASSIGN_USERS_FETCH";
export const ASSIGN_USERS_FETCH_SUCCESS = "ASSIGN_USERS_FETCH_SUCCESS";

export const ASSIGN_USER_SAVE = "ASSIGN_USER_SAVE";
export const ASSIGN_USER_SAVE_SUCCESS = "ASSIGN_USER_SAVE_SUCCESS";
