import NAMESPACE from "./namespace";

export const ASSIGN_USERS_FETCH = `${NAMESPACE}/ASSIGN_USERS_FETCH`;
export const ASSIGN_USERS_FETCH_SUCCESS = `${NAMESPACE}/ASSIGN_USERS_FETCH_SUCCESS`;
export const CLEAR_ERRORS = `${NAMESPACE}/CLEAR_ERRORS`;
export const ASSIGN_USER_SAVE = `${NAMESPACE}/ASSIGN_USER_SAVE`;
export const ASSIGN_USER_SAVE_SUCCESS = `${NAMESPACE}/ASSIGN_USER_SAVE_SUCCESS`;
export const ASSIGN_USER_SAVE_STARTED = `${NAMESPACE}/ASSIGN_USER_SAVE_STARTED`;
export const ASSIGN_USER_SAVE_FAILURE = `${NAMESPACE}/ASSIGN_USER_SAVE_FAILURE`;
export const ASSIGN_USER_SAVE_FINISHED = `${NAMESPACE}/ASSIGN_USER_SAVE_FINISHED`;
