# frozen_string_literal: true

json.id webpush_subscription.id
json.user_id webpush_subscription.user_id
json.disabled webpush_subscription.disabled
json.notification_url webpush_subscription.notification_url
json.created_at webpush_subscription.created_at
json.updated_at webpush_subscription.updated_at
