# frozen_string_literal: true

# Copyright (c) 2014 - 2023 UNICEF. All rights reserved.

# This middleware silences logs generated by endpoints configured under Rails.configuration.silence_logging.
# The endpoints are an array of strings of HTTP methods an paths; eg. ['GET /health', ...]
class LogSilencer
  def initialize(app)
    @app = app
  end

  def call(env)
    if silence_endpoint?(env)
      ::Rails.logger.silence { @app.call(env) }
    else
      @app.call(env)
    end
  end

  def silence_endpoint?(env)
    # TODO: Consider allowing some form of regex
    endpoint = "#{env['REQUEST_METHOD']} #{env['REQUEST_PATH']}".delete_suffix('/').strip
    return false unless endpoint.present?

    Rails.configuration&.silence_logging&.include?(endpoint)
  end
end
