import NAMESPACE from "./namespace";

export const FETCH_DATA = `${NAMESPACE}/FETCH_DATA`;
export const FETCH_DATA_SUCCESS = `${NAMESPACE}/FETCH_DATA_SUCCESS`;
export const FETCH_DATA_STARTED = `${NAMESPACE}/FETCH_DATA_STARTED`;
export const FETCH_DATA_FINISHED = `${NAMESPACE}/FETCH_DATA_FINISHED`;
export const FETCH_DATA_FAILURE = `${NAMESPACE}/FETCH_DATA_FAILURE`;
