import NAMESPACE from "./namespace";

export const FETCH_SYSTEM_SETTINGS = `${NAMESPACE}/FETCH_SYSTEM_SETTINGS`;
export const FETCH_SYSTEM_SETTINGS_SUCCESS = `${NAMESPACE}/FETCH_SYSTEM_SETTINGS_SUCCESS`;
export const SET_USER_IDLE = `${NAMESPACE}/SET_USER_IDLE`;
export const NETWORK_STATUS = `${NAMESPACE}/NETWORK_STATUS`;
