import NAMESPACE from "./namespace";

export const CALCULATE_OFFLINE_ENCRYPTION = `${NAMESPACE}/CALCULATE_OFFLINE_ENCRYPTION`;
export const SET_OFFLINE_ENCRYPTION = `${NAMESPACE}/SET_OFFLINE_ENCRYPTION`;
export const SET_OFFLINE_ENCRYPTION_KEY = `${NAMESPACE}/SET_OFFLINE_ENCRYPTION_KEY`;

export const OFFLINE_SAVE_RECORD = `${NAMESPACE}/OFFLINE_SAVE_RECORD`;
