export const TEXT_FIELD = "text_field";
export const TEXT_AREA = "textarea";
export const FORM_MODE_SHOW = "show";
export const FORM_MODE_EDIT = "edit";
export const FORM_MODE_NEW = "new";
export const FORM_MODE_DIALOG = "dialog";

// TODO: types below need to be implemented;
// export const NUMERIC_FIELD = "numeric_field";
// export const SUBFORM_SECTION = "subform";
// export const DATE_FIELD = "date_field";
export const SELECT_FIELD = "select_box";
export const TICK_FIELD = "tick_box";
export const CHECK_BOX_FIELD = "check_boxes";
// export const SEPERATOR = "separator";
// export const RADIO_FIELD = "radio_button";
// export const PHOTO_FIELD = "photo_upload_box";
// export const DOCUMENT_FIELD = "document_upload_box";
// export const AUDIO_FIELD = "audio_upload_box";
// export const NAME_FIELD = "name";
