// Copyright (c) 2014 - 2023 UNICEF. All rights reserved.

import { Record, fromJS } from "immutable";

import { SELECT_CHANGE_REASON } from "./constants";

export const FieldRecord = Record({
  additionalOptions: [],
  asyncAction: () => {},
  asyncOptions: false,
  asyncOptionsLoadingPath: null,
  asyncParams: {},
  asyncParamsFromWatched: {},
  autoFocus: false,
  autosum_total: true,
  check_errors: fromJS([]),
  clearDependentReason: [SELECT_CHANGE_REASON.selectOption, SELECT_CHANGE_REASON.clear],
  clearDependentValues: null,
  collapse: null,
  currRecord: null,
  date_include_time: false,
  date_validation: null,
  disableClearable: false,
  disabled: null,
  display_conditions_record: undefined,
  display_conditions_subform: undefined,
  display_name: fromJS({}),
  downloadButtonLabel: "",
  editable: true,
  extraSelectorOptions: {},
  fileFormat: "",
  filterOptionSource: null,
  forceShowIf: false,
  form_section_id: null,
  form_section_name: null,
  freeSolo: false,
  groupBy: null,
  guiding_questions: "",
  handleWatchedInputs: null,
  help_text: fromJS({}),
  hide_on_view_page: false,
  hideOnShow: false,
  hint: "",
  href: null,
  i18nDescription: false,
  i18nName: false,
  id: null,
  inlineCheckboxes: false,
  inputClassname: null,
  internalFormFieldID: null,
  link_to_form: "",
  max_length: null,
  maxOptionsAllowed: null,
  maxSelectedOptions: null,
  mobile_visible: false,
  multi_select: null,
  multipleLimitOne: false,
  name: "",
  numeric: false,
  on_collapsed_subform: false,
  onBlur: null,
  onChange: null,
  onClick: null,
  onKeyPress: null,
  option_strings_condition: null,
  option_strings_source_id_key: null,
  option_strings_source: null,
  option_strings_text: null,
  optionFieldName: null,
  order: null,
  password: false,
  placeholder: "",
  rawOptions: false,
  renderChildren: true,
  renderDownloadButton: false,
  required: false,
  selected_value: "",
  setOtherFieldValues: null,
  show_on_minify_form: false,
  showDefaultAction: true,
  showDeleteAction: true,
  showDisableOption: true,
  showIf: null,
  subform_section_configuration: null,
  subform_section_id: null,
  subform_section_temp_id: null,
  subform_section_unique_id: null,
  subform_sort_by: "",
  tally: {},
  tick_box_label: fromJS({}),
  tooltip: "",
  type: "",
  visible: null,
  watchedInputs: null,
  wrapWithComponent: null
});

export const FormSectionRecord = Record({
  actions: null,
  check_errors: fromJS([]),
  collapsed_field_names: fromJS([]),
  core_form: false,
  description: fromJS({}),
  editable: null,
  expandable: false,
  expanded: false,
  fields: fromJS([]),
  form_group_id: "",
  form_group_name: "",
  id: "",
  initial_subforms: 0,
  is_first_tab: null,
  is_nested: null,
  i18nDescription: false,
  i18nName: false,
  module_ids: fromJS([]),
  name: fromJS({}),
  order_form_group: null,
  order: null,
  parent_form: "",
  subform_append_only: false,
  subform_prevent_item_removal: false,
  temp_id: null,
  tooltip: "",
  unique_id: "",
  visible: null
});

export const Option = Record({
  options: fromJS([]),
  type: ""
});
