#!/bin/bash

cat <<EOH > /etc/couchdb/local.d/admin.ini
[admins]
primero = ${COUCHDB_PASSWORD}
EOH

chown -R couchdb.couchdb /var/log/couchdb
chown -R couchdb.couchdb /var/lib/couchdb
chown couchdb.couchdb -R /etc/couchdb
mkdir -p /var/run/couchdb
chown -R couchdb.couchdb /var/run/couchdb

exec $@
