turnstile:
  js_client: 'https://challenges.cloudflare.com/turnstile/v0/api.js'
  challenge_url: 'https://challenges.cloudflare.com/turnstile/v0/siteverify'
  secret_key: <%= ENV['PRIMERO_CAPTCHA_SECRET_KEY'] %>
  site_key: <%= ENV['PRIMERO_CAPTCHA_SITE_KEY'] %>