import { namespaceActions } from "../../../../libs";
import NAMESPACE from "../namespace";

export default namespaceActions(NAMESPACE, [
  "CLEAR_SELECTED_CONFIGURATION",
  "FETCH_CONFIGURATION",
  "FETCH_CONFIGURATION_STARTED",
  "FETCH_CONFIGURATION_SUCCESS",
  "FETCH_CONFIGURATION_FINISHED",
  "FETCH_CONFIGURATION_FAILURE",
  "SAVE_CONFIGURATION",
  "SAVE_CONFIGURATION_STARTED",
  "SAVE_CONFIGURATION_FINISHED",
  "SAVE_CONFIGURATION_SUCCESS",
  "SAVE_CONFIGURATION_FAILURE"
]);
