export const CASES_BY_NATIONALITY = "Reports/CASES_BY_NATIONALITY";
export const CASES_BY_AGE_AND_SEX = "Reports/CASES_BY_AGE_AND_SEX";
export const CASES_BY_PROTECTION_CONCERN =
  "Reports/CASES_BY_PROTECTION_CONCERN";
export const CASES_BY_AGENCY = "Reports/CASES_BY_AGENCY";
