export const FETCH_REPORTS = "Reports/FETCH_REPORTS";
export const FETCH_REPORTS_SUCCESS = "Reports/FETCH_REPORTS_SUCCESS";
export const FETCH_REPORTS_FAILURE = "Reports/FETCH_REPORTS_FAILURE";
export const FETCH_REPORT = "Reports/FETCH_REPORT";
export const FETCH_REPORT_SUCCESS = "Reports/FETCH_REPORT_SUCCESS";
export const FETCH_REPORT_FAILURE = "Reports/FETCH_REPORT_FAILURE";
