import NAMESPACE from "./namespace";

export const FETCH_SAVED_SEARCHES = `${NAMESPACE}/FETCH_SAVED_SEARCHES`;
export const FETCH_SAVED_SEARCHES_SUCCESS = `${NAMESPACE}/FETCH_SAVED_SEARCHES_SUCCESS`;
export const SAVE_SEARCH = `${NAMESPACE}/SAVE_SEARCH`;
export const SAVE_SEARCH_SUCCESS = `${NAMESPACE}/SAVE_SEARCH_SUCCESS`;
export const REMOVE_SAVED_SEARCH = `${NAMESPACE}/REMOVE_SAVED_SEARCH`;
export const REMOVE_SAVED_SEARCH_SUCCESS = `${NAMESPACE}/REMOVE_SAVED_SEARCH_SUCCESS`;
