import NAMESPACE from "./namespace";

export const ENQUEUE_SNACKBAR = `${NAMESPACE}/ENQUEUE_SNACKBAR`;
export const CLOSE_SNACKBAR = `${NAMESPACE}/CLOSE_SNACKBAR`;
export const REMOVE_SNACKBAR = `${NAMESPACE}/REMOVE_SNACKBAR`;
