require_relative 'bia_form_family_nested_forms.rb'
require_relative 'bia_form_child_wishes_nested_forms.rb'
require_relative 'bia_form_child_other_wishes_nested_forms.rb'
require_relative 'bia_form_care_arrangements_nested_forms.rb'
require_relative 'bia_form_people_interviewed_nested_forms.rb'
require_relative 'bia_form_interventions_nested_forms.rb'
require_relative 'bia_form_followups_nested_forms.rb'
require_relative 'bia_form_transfers_nested_forms.rb'

bia_fields = [
    Field.new({"name" => "bia_approved",
               "type" => "tick_box",
               "tick_box_label_all" => "Yes",
               "display_name_all" => "Approved by Manager",
               "disabled" => true
              }),
    Field.new({"name" => "bia_approved_date",
               "type" => "date_field",
               "display_name_all" => "Date",
               "disabled" => true
              }),
    Field.new({"name" => "bia_approved_comments",
               "type" => "textarea",
               "display_name_all" => "Manager Comments",
               "disabled" => true
              }),
    Field.new({"name" => "approval_status_bia",
               "type" => "select_box",
               "display_name_all" => "Approval Status",
               "option_strings_text_all" =>
                   ["Pending",
                    "Approved",
                    "Rejected"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "case_id_display",
               "type" => "text_field",
               "display_name_all" => "Primero Case ID",
               "disabled" => true,
              }),
    Field.new({"name" => "bia_header",
               "type" => "separator",
               "display_name_all" => "ASSESSMENT FORM (for completion for all Child Protection cases including UASC)",
               "disabled" => true,
              }),
    Field.new({"name" => "case_priority",
               "type" => "select_box",
               "display_name_all" => "Priority",
               "disabled" => true,
               "option_strings_text_all" =>
                   ["2 days",
                    "1 week",
                    "30 days",
                    "Non Urgent (enter date)"].join("\n")
              }),
    Field.new({"name" => "case_priority_date",
               "type" => "date_field",
               "display_name_all" => "Re-assessment date",
               "disabled" => true
              }),
    Field.new({"name" => "cpims_id",
               "type" => "text_field",
               "display_name_all" => "CPIMS No",
               "disabled" => true
              }),
    Field.new({"name" => "other_org_interview_status",
               "type" => "radio_button",
               "display_name_all" => "Has the child been previously interviewed and registered by a Child Protection Agency in Jordan?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "other_org_interview_type",
               "type" => "select_box",
               "multi_select" => true,
               "display_name_all" => "If yes, enter the organization types that conducted the interview(s)",
               "disabled" => true,
               "help_text_all" => "Select all that apply",
               "option_strings_text_all" =>
                   ["UN Agency",
                    "INGOs",
                    "Gvrt Department",
                    "Civil Society",
                    "NGOs",
                    "Other"].join("\n")
              }),
    Field.new({"name" => "other_org_interview_type_other",
               "type" => "text_field",
               "display_name_all" => "If Other, please enter the name (or names) here",
               "disabled" => true
              }),
    Field.new({"name" => "interviewer_agency_service_type",
               "type" => "select_box",
               "multi_select" => true,
               "display_name_all" => "If the child was previously interviewed, note the types of services the provider gave",
               "disabled" => true,
               "help_text_all" => "Select all that apply",
               "option_strings_text_all" =>
                   ["Protection",
                    "Education",
                    "Food",
                    "Health",
                    "NFIs",
                    "WASH",
                    "Financial assistance",
                    "Shelter",
                    "Other",
                    "None"].join("\n")
              }),
    Field.new({"name" => "interviewer_agency_service_details",
               "type" => "textarea",
               "display_name_all" => "If services were provided, note any information given on the provider and services they gave",
               "disabled" => true
              }),
    Field.new({"name" => "bia_consent_section",
               "type" => "separator",
               "display_name_all" => "CONSENT FOR SHARING INFORMATION",
               "disabled" => true
              }),
    Field.new({"name" => "consent_obtained",
               "type" => "radio_button",
               "display_name_all" => "Have you completed the confidentiality agreement with the client?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "data_protection_issue",
               "type" => "radio_button",
               "display_name_all" => "Is there a data protection issue with this client?",
               "help_text_all" => "If yes, refer to consent form while managing case",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "photo_taken",
               "type" => "radio_button",
               "display_name_all" => "Have you taken a photo of the child?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "bia_identity_section",
               "type" => "separator",
               "display_name_all" => "SECTION 1 - CHILD'S PERSONAL DETAILS (BIO-DATA)",
               "disabled" => true
              }),
    Field.new({"name" => "name_first",
               "type" => "text_field",
               "display_name_all" => "First Name",
               "help_text_all" => "Enter English / Arabic names.",
               "disabled" => true
              }),
    Field.new({"name" => "name_middle",
               "type" => "text_field",
               "display_name_all" => "Father Name",
               "help_text_all" => "Enter English / Arabic names.",
               "disabled" => true
              }),
    Field.new({"name" => "name_middle_other",
               "type" => "text_field",
               "display_name_all" => "Grandfather Name",
               "help_text_all" => "Enter English / Arabic names.",
               "disabled" => true
              }),
    Field.new({"name" => "name_last",
               "type" => "text_field",
               "display_name_all" => "Family Name",
               "help_text_all" => "Enter English / Arabic names.",
               "disabled" => true
              }),
    Field.new({"name" => "name_nickname",
               "type" => "text_field",
               "display_name_all" => "Nickname / Alias",
               "help_text_all" => "Enter English / Arabic names.",
               "disabled" => true
              }),
    Field.new({"name" => "address_separation",
               "type" => "textarea",
               "editable" => true,
               "display_name_all" => "Separation Address",
               "disabled" => true
              }),
    Field.new({"name" => "landmark_separation",
               "type" => "textarea",
               "editable" => true,
               "display_name_all" => "Separation Landmark",
               "disabled" => true
              }),
    Field.new({"name" => "location_separation",
               "type" => "select_box",
               "display_name_all" => "Separation Location",
               "disabled" => true,
               "option_strings_source" => "Location"
            }),
    Field.new({"name" => "address_current",
               "type" => "textarea",
               "display_name_all" => "Current Address",
               "disabled" => true
              }),
    Field.new({"name" => "landmark_current",
               "type" => "text_field",
               "display_name_all" => "Landmark",
               "disabled" => true
              }),
    Field.new({"name" => "location_current",
               "type" =>"select_box",
               "display_name_all" => "Current Location",
               "disabled" => true,
               "option_strings_source" => "Location"
              }),
    Field.new({"name" => "sex",
               "type" => "select_box",
               "option_strings_text_all" => "Male\nFemale",
               "disabled" => true,
               "display_name_all" => "Sex"
              }),
    Field.new({"name" => "age",
               "type" => "numeric_field",
               "disabled" => true,
               "display_name_all" => "Age"
              }),
    Field.new({"name" => "date_of_birth",
               "type" => "date_field",
               "disabled" => true,
               "display_name_all" => "Date of Birth"
              }),
    Field.new({"name" => "unhcr_id_no",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "UN ID No"
              }),
    Field.new({"name" => "national_id_no",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "National ID Number"
              }),
    Field.new({"name" => "ration_card_no",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "Ration Card / Service ID No"
              }),
    Field.new({"name" => "other_agency_id",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "Other ID No (specify kind)"
              }),
    Field.new({"name" => "other_agency_name",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "Other ID Name"
              }),
    Field.new({"name" => "telephone_current",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "Current Telephone"
              }),
    Field.new({"name" => "telephone_other",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "Other Tel. No (specify)"
              }),
    Field.new({"name" => "telephone_other_who",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "Other Telephone Individual"
              }),
    Field.new({"name" => "nationality",
               "type" =>"select_box",
               "multi_select" => true,
               "disabled" => true,
               "display_name_all" => "Citizenship",
               "option_strings_source" => "lookup Nationality"
              }),
    Field.new({"name" => "country_of_origin",
               "type" =>"select_box",
               "disabled" => true,
               "display_name_all" => "Country of Origin",
               "option_strings_source" => "lookup Country"
              }),
    Field.new({"name" => "bia_father",
               "type" => "subform",
               "create_property" => false,
               "editable" => false,
               "disabled" => true,
               "subform_section_id" => "bia_father_family_details",
               "display_name_all" => "Father"
              }),
    Field.new({"name" => "bia_mother",
               "type" => "subform",
               "create_property" => false,
               "editable" => false,
               "disabled" => true,
               "subform_section_id" => "bia_mother_family_details",
               "display_name_all" => "Mother"
              }),
    Field.new({"name" => "not_family_explanation",
               "type" => "textarea",
               "create_property" => false,
               "editable" => true,
               "display_name_all" => "If child has been living with caregivers other than the parents explain why, for how long, and their relationship to the child",
               "disabled" => true,
               "visible" => true
              }),
    Field.new({"name" => "father_death_details",
               "type" => "textarea",
               "create_property" => false,
               "editable" => true,
               "display_name_all" => "If father believed dead, give details including whether information has been verified",
               "disabled" => true,
               "visible" => true
              }),
    Field.new({"name" => "mother_death_details",
               "type" => "textarea",
               "create_property" => false,
               "editable" => true,
               "display_name_all" => "If mother believed dead, give details including whether information has been verified",
               "disabled" => true,
               "visible" => true
              }),
    Field.new({"name" => "bia_male_caregiver",
               "type" => "subform",
               "create_property" => false,
               "editable" => false,
               "disabled" => true,
               "subform_section_id" => "bia_male_caregiver_family_details",
               "display_name_all" => "Male Primary Caregiver"
              }),
    Field.new({"name" => "bia_female_caregiver",
               "type" => "subform",
               "create_property" => false,
               "editable" => false,
               "disabled" => true,
               "subform_section_id" => "bia_female_caregiver_family_details",
               "display_name_all" => "Female Primary Caregiver"
              }),
    #Field.new({"name" => "protection_status",
    #           "type" => "select_box",
    #           "disabled" => true,
    #           "option_strings_source" => "lookup ProtectionStatus",
    #           "display_name_all" => "Child Protection concerns"
    #          }),
    Field.new({"name" => "protection_concern_from_child",
               "type" => "textarea",
               "editable" => true,
               "display_name_all" => "Briefly describe the child's major concern/issue",
               "disabled" => true,
               "visible" => true
              }),
    Field.new({"name" => "source_interview",
               "type" =>"select_box" ,
               "multi_select" => true,
               "disabled" => true,
               "display_name_all" => "Information Obtained From",
               "option_strings_text_all" =>
                          ["Self-Referral",
                          "Identification by CP Community Worker",
                          "CFS",
                          "UNHCR-Registration",
                          "UNHCR-Protection",
                          "Medical Agencies",
                          "Education Provider",
                          "Governmentt SW",
                          "Police",
                          "Community Leaders",
                          "Other Agency"].join("\n")
              }),
    Field.new({"name" => "source_interview_other",
               "type" =>"text_field" ,
               "display_name_all" => "If information obtained from Other Agency, please specify"
              }),
    Field.new({"name" => "identification_date",
               "type" => "date_field",
               "disabled" => true,
               "display_name_all" => "Date of Identification"
              }),
    Field.new({"name" => "arrival_date",
               "type" => "date_field",
               "disabled" => true,
               "display_name_all" => "Date of Arrival in Jordan"
              }),
    Field.new({"name" => "current_location_date",
               "type" => "date_field",
               "disabled" => true,
               "display_name_all" => "Date of Arrival in Current Location"
              }),
    Field.new({"name" => "bia_separated_section",
               "type" => "separator",
               "display_name_all" => "SECTION 2 - Separated and Unaccompanied Children",
               "disabled" => true,
               "visible" => true
              }),
    Field.new({"name" => "details_separation_plans_placement_section",
               "type" => "separator",
               "display_name_all" => "Section 2.1: Details of separation and plans for placement and care",
               "disabled" => true,
               "visible" => true
              }),
    Field.new({"name" => "protection_status",
               "type" => "select_box",
               "option_strings_source" => "lookup ProtectionStatus",
               "disabled" => true,
               "display_name_all" => "Separation Status"
              }),
    Field.new({"name" => "name_other",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "Other Name(s)"
              }),
    Field.new({"name" => "name_given_post_separation",
               "type" => "radio_button",
               "disabled" => true,
               "display_name_all" => "Name(s) given to child after separation?",
               "option_strings_text_all" => "Yes\nNo",
              }),
    Field.new({"name" => "history_separation_section",
               "type" => "separator",
               "display_name_all" => "History and reasons for separation from parents / previous caregiver",
               "disabled" => true
              }),
    Field.new({"name" => "separation_cause",
               "type" => "select_box",
               "display_name_all" => "What was the main cause of separation?",
               "disabled" => true,
               "option_strings_text_all" =>
                        ["For safety",
                         "Death / sickness of caregiver",
                         "Family violence",
                         "Separated at border",
                         "To work",
                         "For Family reunification",
                         "Family returned to Syria without the child",
                         "Child left the camp and caught by the police",
                         "Fear of sexual violence",
                         "To access services",
                         "Targeted for persecution",
                         "Sent ahead of Parents",
                         "To avoid conscription",
                         "Accidental (during flight)",
                         "Other (specify)"].join("\n")
              }),
    Field.new({"name" => "separation_cause_other",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "If Other, please specify"
              }),
    Field.new({"name" => "separation_other_applicable_causes",
               "type" => "select_box",
               "multi_select" => true,
               "disabled" => true,
               "display_name_all" => "If applicable, what were other causes of separation? ",
               "option_strings_text_all" =>
                        ["For safety",
                         "Death / sickness of caregiver",
                         "Family violence",
                         "Separated at border",
                         "To work",
                         "For Family reunification",
                         "Family returned to Syria without the child",
                         "Child left the camp and caught by the police",
                         "Fear of sexual violence",
                         "To access services",
                         "Targeted for persecution",
                         "Sent ahead of Parents",
                         "To avoid conscription",
                         "Accidental (during flight)",
                         "Other (specify)"].join("\n")
              }),
    Field.new({"name" => "separation_details",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "How, when and where was the child separated from their parents / previous primary caregiver"
              }),
    Field.new({"name" => "separation_additional_movements",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "List any movements between place of separation and current location"
              }),
    Field.new({"name" => "how_entered_jordan",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "How and why the child entered Jordan"
              }),
    Field.new({"name" => "info_other_caregivers",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Information on any other caregivers the child had in between the previous primary caregiver and the current caregiver"
              }),
    Field.new({"name" => "wishes_contacted",
               "type" => "radio_button",
               "disabled" => true,
               "display_name_all" => "Is the child in contact with their previous primary caregivers?",
               "option_strings_text_all" => "Yes\nNo",
              }),
    Field.new({"name" => "in_contact_caregiver_telephone",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "Telephone Number"
              }),
    Field.new({"name" => "how_frequent_contact",
               "type" =>"select_box" ,
               "disabled" => true,
               "display_name_all" => "How frequent is the contact?",
               "option_strings_text_all" =>
                          ["Daily",
                           "Weekly",
                           "Infrequently"].join("\n")
              }),
    Field.new({"name" => "wishes_child_family_tracing",
               "type" => "radio_button",
               "disabled" => true,
               "display_name_all" => "Does the child need their previous primary caregiver or other primary relatives to be traced (i.e. if they are not in contact)?",
               "option_strings_text_all" => "Yes\nNo"
              }),
    Field.new({"name" => "bia_child_wishes",
               "type" => "subform",
               "create_property" => false,
               "editable" => false,
               "disabled" => true,
               "subform_section_id" => "bia_child_wishes_subform",
               "display_name_all" => "Child's Preferences"
              }),
    Field.new({"name" => "other_people_info_tracing",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Others who may be able to provide information to help with tracing?"
              }),
    Field.new({"name" => "consent_for_tracing",
               "type" => "radio_button",
               "disabled" => true,
               "display_name_all" => "Does the child / caregiver consent to tracing?",
               "option_strings_text_all" => "Yes\nNo"
              }),
    Field.new({"name" => "documents_carried",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "List any documents carried by the child or caregiver"
              }),
    Field.new({"name" => "other_wishes_relatives",
               "type" => "radio_button",
               "disabled" => true,
               "display_name_all" => "Does child have any other relatives/friends in Jordan?",
               "option_strings_text_all" => "Yes\nNo"
              }),
    Field.new({"name" => "join_other_wishes_relatives",
               "type" => "radio_button",
               "disabled" => true,
               "display_name_all" => "Does the child plan to join these people at any time?",
               "option_strings_text_all" => "Yes\nNo"
              }),
    Field.new({"name" => "bia_child_other_wishes",
               "type" => "subform",
               "create_property" => false,
               "editable" => false,
               "disabled" => true,
               "subform_section_id" => "bia_child_other_wishes_subform",
               "display_name_all" => "Child's Other Preferences "
              }),
    Field.new({"name" => "current_care_arrangements_section",
               "type" => "separator",
               "display_name_all" => "Section 2.2 - Current Care Arrangements",
               "disabled" => true
              }),
    Field.new({"name" => "current_care_arrangements",
               "type" => "subform",
               "create_property" => false,
               "editable" => false,
               "disabled" => true,
               "subform_section_id" => "bia_current_care_arrangements_subform",
               "display_name_all" => "Current Care Arrangements"
              }),
    Field.new({"name" => "child_in_adult_care_section",
               "type" => "separator",
               "display_name_all" => "IF THE CHILD IS IN ADULT CARE COMPLETE THIS SECTION:",
               "disabled" => true
              }),
    Field.new({"name" => "caregiver_nationality_other",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "Other Citizenship"
              }),
    Field.new({"name" => "unaccompanied_children_foster_care_section",
               "type" => "separator",
               "display_name_all" => "FOR ALL UNACCOMPANIED CHILDREN IN INFORMAL FOSTER CARE:",
               "disabled" => true
              }),
    Field.new({"name" => "child_without_adult_care_separator",
               "type" => "separator",
               "display_name_all" => "IF THE CHILD IS WITHOUT ADULT CARE COMPLETE THIS SECTION:",
               "disabled" => true
              }),
    Field.new({"name" => "for_all_unaccompanied_children_separator",
               "type" => "separator",
               "display_name_all" => "FOR ALL UNACCOMPANIED CHILDREN:",
               "disabled" => true
              }),
    Field.new({"name" => "bia_assessment_section",
               "type" => "separator",
               "display_name_all" => "Secion 3 - ASSESSMENT OF CHILD'S CURRENT SITUATION",
               "disabled" => true
              }),
    Field.new({"name" => "assessment_daily_separator",
               "type" => "separator",
               "display_name_all" => "3.1 Daily Activities and Social Relations",
               "disabled" => true
              }),
    Field.new({"name" => "assessment_daily_time_spent",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Apart from school or work, how does the child spend their day?"
              }),
    Field.new({"name" => "assessment_daily_time_spent_other_children",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Do they spend time with other children?"
              }),
    Field.new({"name" => "assessment_daily_other",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Does the child mix with his/her peers and take part in the usual recreational and other activities?"
              }),
    Field.new({"name" => "assessment_daily_different",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Does the child feel different or feel they are treated differently to their peers?"
              }),
    Field.new({"name" => "assessment_emotional_separator",
               "type" => "separator",
               "display_name_all" => "3.2 Emotional Wellbeing",
               "disabled" => true
              }),
    Field.new({"name" => "assessment_emotional_concerns",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "What are the child's main concerns or worries?"
              }),
    Field.new({"name" => "assessment_emotional_problems",
               "type" =>"select_box" ,
               "multi_select" => true,
               "disabled" => true,
               "display_name_all" => "Does the child appear to have any emotional problems or behavioural problems?",
               "option_strings_text_all" =>
                          ["Frightened",
                           "Withdrawn",
                           "Unhappy",
                           "Difficulties sleeping",
                           "Aggressiveness",
                           "Difficulties concentrating",
                           "Conflict with others",
                           "Lack of confidence",
                           "Other"].join("\n")
              }),
    Field.new({"name" => "assessment_emotional_problems_other",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "If Other, please specify "
              }),
    Field.new({"name" => "assessment_emotional_coping",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "How do they cope with their problems?"
              }),
    Field.new({"name" => "assessment_emotional_support_persons",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Do they have support from people around them to deal with their problems, and if so from whom?"
              }),
    Field.new({"name" => "assessment_emotional_stress",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Does the child appear to be extremely distressed and/or have difficulty functioning in their daily life?"
              }),
    Field.new({"name" => "assesment_emotional_witness_violence",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Has the child witnessed or experienced violence?"
              }),
    Field.new({"name" => "activities_education_separator",
               "type" => "separator",
               "display_name_all" => "3.3 Education, Skills and Livelihoods Assessment",
               "disabled" => true
              }),
    Field.new({"name" => "activities_country_origin",
               "type" => "select_box" ,
               "multi_select" => true,
               "disabled" => true,
               "display_name_all" => "What did the child do in their country of origin?",
               "option_strings_text_all" =>
                          ["School",
                           "Unpaid work",
                           "Paid work",
                           "Recreational activities",
                           "Other (Specify)"].join("\n")
              }),
    Field.new({"name" => "activities_country_origin_other",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "If Other, please specify   "
              }),
    Field.new({"name" => "activities_household_country_origin",
               "type" => "numeric_field",
               "disabled" => true,
               "display_name_all" => "How many hours per day did the child spend on activities for the household (chores, other) in their country of origin?"
              }),
    Field.new({"name" => "activities_country_now",
               "type" => "select_box" ,
               "multi_select" => true,
               "disabled" => true,
               "display_name_all" => "What does the child do in Jordan?",
               "option_strings_text_all" =>
                          ["School",
                           "Unpaid work",
                           "Paid work",
                           "Recreational activities",
                           "Other (Specify)"].join("\n")
              }),
    Field.new({"name" => "activities_country_now_other",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "If Other, please specify    "
              }),
    Field.new({"name" => "activities_household_country_now",
               "type" => "numeric_field",
               "disabled" => true,
               "display_name_all" => "How many hours per day does the child spend on activities for the household (chores, other) in Jordan?"
              }),
    Field.new({"name" => "working_country_now",
               "type" => "select_box" ,
               "multi_select" => true,
               "disabled" => true,
               "display_name_all" => "If the child is working, tick all that applies:",
               "option_strings_text_all" =>
                          ["Paid work under 16",
                           "Paid work over 16, 6 hours / day or less",
                           "Paid work over 16, more than 6 hours / day",
                           "Work is harmful for child's development",
                           "Worst forms of child labour",
                           "Family or child depend on child's income"].join("\n")
              }),
    Field.new({"name" => "activities_child_in_school_or_training",
               "type" => "radio_button",
               "display_name_all" => "Is the Child in school or training?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "activities_reason_not_in_school_text",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "If not, why not?"
              }),
    Field.new({"name" => "activities_want_school",
               "type" => "select_box",
               "disabled" => true,
               "display_name_all" => "If not in school,would the child like to go to school?",
               "option_strings_text_all" => ["Yes", "No", "Not Sure"].join("\n")
              }),
    Field.new({"name" => "activities_education_type",
               "type" => "select_box",
               "disabled" => true,
               "display_name_all" => "If yes, what type of education?",
               "option_strings_text_all" =>
                          ["Accelerated learning",
                          "Early Childhood",
                          "Non-Formal Education",
                          "Primary",
                          "Secondary",
                          "Vocational",
                          "Vocational training"].join("\n")
              }),
    Field.new({"name" => "activities_level_achieved",
               "type" => "select_box",
               "disabled" => true,
               "display_name_all" => "If relevant, what level have they achieved?",
               "option_strings_text_all" =>
                          ["Carpentry",
                           "GS1", "GS2", "GS3",
                           "level 1", "level 2",
                           "level 3", "level 4",
                           "SS1", "SS2", "SS3",
                           "Tailoring",
                           "Woodwork",
                           "Hairdressing"].join("\n")
              }),
    Field.new({"name" => "activities_attendance",
               "type" => "select_box",
               "disabled" => true,
               "display_name_all" => "If the child is in school or training, how regularly do they attend?",
               "option_strings_text_all" =>
                          ["Occassionally",
                           "One day a week or less",
                           "Several days a week",
                           "Everyday"].join("\n")
              }),
    Field.new({"name" => "activities_education_attitude",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Briefly describe child's attitude toward school and if they have any problems at school"
              }),
    Field.new({"name" => "activities_working",
               "type" => "radio_button",
               "display_name_all" => "Is the child working?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "activities_working_number_hours",
               "type" => "select_box",
               "disabled" => true,
               "display_name_all" => "If yes, how many hours a day?",
               "option_strings_text_all" =>
                          ["< 1", "2 - 4", "5 - 8", "9 - 12", "> 12"].join("\n")
              }),
    Field.new({"name" => "activities_working_number_days",
               "type" => "select_box",
               "disabled" => true,
               "display_name_all" => "If yes, how many days a week?",
               "option_strings_text_all" =>
                          ["1", "2", "3", "4", "5", "6", "7"].join("\n")
              }),
    Field.new({"name" => "activities_working_type",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Describe the type of work"
              }),
    Field.new({"name" => "activities_working_impact",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Describe the impact of working"
              }),
    Field.new({"name" => "activities_working_reason",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "What is the main reason the child works?"
              }),
    Field.new({"name" => "activities_working_family_details",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "How many people are working? Do they run any businesses? Do they receive any income support? Do they have any assets? Can they provide their basic needs? Did they work or have businesses in the country of origin (if, yes, give details)?"
              }),
    Field.new({"name" => "activities_working_family_income",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "What is the family's gross monthly income?"
              }),
    Field.new({"name" => "activities_working_family_rent",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "How much is the rent (in Host Community)?"
              }),
    Field.new({"name" => "activities_working_family_utilities",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "How much do their utilities cost?"
              }),
    Field.new({"name" => "health_and_nutrition_needs_separator",
               "type" => "separator",
               "display_name_all" => "3.4 Health and Nutrition Needs",
               "disabled" => true
              }),
    Field.new({"name" => "assessment_health_needs",
               "type" => "radio_button",
               "display_name_all" => "Does the child have any immediate medical needs or long-term health concerns?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "assessment_medical_access",
               "type" => "radio_button",
               "display_name_all" => "Does the child have access to medical care?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "assessment_no_medical_access_reason",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "If not, why not?  "
              }),
    Field.new({"name" => "assessment_meals_per_day",
               "type" => "select_box",
               "disabled" => true,
               "display_name_all" => "How many meals a day does the child have?",
               "option_strings_text_all" => ["0", "1", "2", "3"].join("\n")
              }),
    Field.new({"name" => "assessment_camp_food_rations",
               "type" => "radio_button",
               "display_name_all" => "In the camp - is the family receiving food rations?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "assessment_host_communities_cash",
               "type" => "radio_button",
               "display_name_all" => "In the host communities - is the family receiving cash assistance?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "assessment_enough_food",
               "type" => "radio_button",
               "display_name_all" => "Does the child have enough to eat?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "assessment_not_enough_food_reason",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "If not, why not?   "
              }),
    Field.new({"name" => "basic_survival_needs_separator",
               "type" => "separator",
               "display_name_all" => "3.5 Basic Survival Needs (and home setting)",
               "disabled" => true
              }),
    Field.new({"name" => "assessment_clothing",
               "type" => "radio_button",
               "display_name_all" => "Does the child have sufficient clothing?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "assessment_clean_water",
               "type" => "radio_button",
               "display_name_all" => "Does the child have acces to clean water?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "assessment_clean_toliets_showers",
               "type" => "radio_button",
               "display_name_all" => "Are they able to access safe, clean toilets and showers?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "assessment_no_clean_toliets_showers_reason",
               "type" => "radio_button",
               "display_name_all" => "If not, explain ",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "assessment_living_situation",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Describe the child's living / accommodation situation - the number of rooms in the home, how many people live there, if the accommodation is shared with any other family, if there are any ventilation or damp issues."
              }),
    Field.new({"name" => "family_assessment_separator",
               "type" => "separator",
               "display_name_all" => "3.6 Family Assessment (family relationships)",
               "disabled" => true
              }),
    Field.new({"name" => "assessment_happy_in_home",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Does the child appear happy in the home (give examples)?"
              }),
    Field.new({"name" => "assessment_risk_factors",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Risk Factors"
              }),
    Field.new({"name" => "assessment_protection_factors",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Protection Factors"
              }),
    Field.new({"name" => "bia_protection_concerns_separator",
               "type" => "separator",
               "display_name_all" => "3.7 Protection Concerns",
               "disabled" => true
              }),
    Field.new({"name" => "assessment_feel_safe",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "Does the child feel safe in their daily life?"
              }),
    Field.new({"name" => "assessment_safety_concerns",
               "type" => "radio_button",
               "display_name_all" => "Are there any immediate safety concerns with the child?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "assessment_safety_concerns_detail",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "If so, describe them here"
              }),
    #Field.new({"name" => "protection_status",
    #           "type" => "select_box",
    #           "disabled" => true,
    #           "option_strings_source" => "lookup ProtectionStatus",
    #           "display_name_all" => "Primary Protection Concern"
    #          }),
    Field.new({"name" => "unhcr_needs_codes",
               "type" => "select_box",
               "multi_select" => true,
               "display_name_all" => "UNHCR Needs Codes",
               "disabled" => false,
               "option_strings_source" => "lookup UnhcrNeedsCodes"
              }),
    Field.new({"name" => "bia_wishes_child",
               "type" => "separator",
               "display_name_all" => "Section 4 - WISHES OF THE CHILD",
               "disabled" => true
              }),
    Field.new({"name" => "bia_wishes_child_intervention",
               "type" => "radio_button",
               "display_name_all" => "Does the child wish for intervention or particular support in relation to any of the above areas?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "bia_wishes_child_intervention_details",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "If yes, give details"
              }),
    Field.new({"name" => "intervention_in_conflict_wishes_child",
               "type" => "radio_button",
               "display_name_all" => "If the assessment shows the need for intervention that is in addition or in conflict with the wishes of the child, has this been discussed with the child?",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "intervention_in_conflict_wishes_child_reason",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "If not, why not? If this has been discussed what is the outcome?"
              }),
    Field.new({"name" => "steps_to_ensure_safety",
               "type" => "textarea",
               "disabled" => true,
               "display_name_all" => "If the child is at risk, outline what steps are needed to ensure their safety and well-being"
              }),
    Field.new({"name" => "addition_info_caregiver",
               "type" => "separator",
               "display_name_all" => "SECTION 5 - Additional information / Consideration from the caregivers",
               "disabled" => true
              }),
    Field.new({"name" => "bia_interviews",
               "type" => "subform",
               "create_property" => false,
               "editable" => false,
               "disabled" => true,
               "subform_section_id" => "bia_interviews_subform",
               "display_name_all" => "Caregivers Interviewed"
              }),
    Field.new({"name" => "proposed_interventions_section",
               "type" => "separator",
               "display_name_all" => "SECTION 6 - PROPOSED INTERVENTION / RECOMMENDATIONS",
               "disabled" => true
              }),
    Field.new({"name" => "bia_interventions",
               "type" => "subform",
               "create_property" => false,
               "editable" => false,
               "disabled" => true,
               "subform_section_id" => "bia_interventions_subform",
               "display_name_all" => "List of Interventions and Services "
              }),
    Field.new({"name" => "bia_consent_for_services",
               "type" => "tick_box",
               "create_property" => false,
               "tick_box_label_all" => "Yes",
               "display_name_all" => "Consent has been obtained for the child to receive services",
               "disabled" => true
              }),
    Field.new({"name" => "direct_actions_to_be_taken_separator",
               "type" => "separator",
               "display_name_all" => "Direct Actions to be Taken by the Case Worker",
               "disabled" => true
              }),
    Field.new({"name" => "bia_followups",
               "type" => "subform",
               "create_property" => false,
               "editable" => false,
               "disabled" => true,
               "subform_section_id" => "bia_followups_subform",
               "display_name_all" => "Followups"
              }),
    Field.new({"name" => "case_transferred_for_bia",
               "type" => "radio_button",
               "display_name_all" => "Case transferred to another agency",
               "option_strings_text_all" => ["Yes", "No"].join("\n"),
               "disabled" => true
              }),
    Field.new({"name" => "bia_transfers",
               "type" => "subform",
               "create_property" => false,
               "editable" => false,
               "disabled" => true,
               "subform_section_id" => "bia_transfers_subform",
               "display_name_all" => "Transfers"
              }),
    Field.new({"name" => "form_completed_header",
               "type" => "separator",
               "display_name_all" => "SECTION 7 - FORM COMPLETED / APPROVED BY",
               "disabled" => true
              }),
    Field.new({"name" => "interviewer_name",
               "type" => "text_field",
               "disabled" => true,
               "display_name_all" => "Interviewer Name"
              }),
    Field.new({"name" => "interview_date",
               "type" => "date_field",
               "display_name_all" => "Interview Date",
               "disabled" => true
              })
] 

FormSection.create_or_update_form_section({
    :unique_id => "bia_form_config_generation_only",
    :parent_form=>"",
    "visible" => false,
    :order_form_group => 136,
    :order => 10,
    :order_subform => 0,
    :form_group_name => "BIA Form config generation only",
    "editable" => true,
    :fields => bia_fields,
    "name_all" => "BIA Form config generation only",
    "description_all" => "BIA Form config generation only"
})
