import NAMESPACE from "./namespace";

export const TASKS = `${NAMESPACE}/TASKS`;
export const TASKS_STARTED = `${NAMESPACE}/TASKS_STARTED`;
export const TASKS_SUCCESS = `${NAMESPACE}/TASKS_SUCCESS`;
export const TASKS_FINISHED = `${NAMESPACE}/TASKS_FINISHED`;
export const TASKS_FAILURE = `${NAMESPACE}/TASKS_FAILURE`;
