export const RECORDS_FAILURE = "RECORDS_FAILURE";
export const RECORDS_STARTED = "RECORDS_STARTED";
export const RECORDS_FINISHED = "RECORDS_FINISHED";
export const RECORDS_SUCCESS = "RECORDS_SUCCESS";
export const RECORDS = "RECORDS";
export const SET_PAGINATION = "SET_PAGINATION";
