export const RECORDS_FAILED = "RECORDS_FAILED";
export const RECORDS_STARTED = "RECORDS_STARTED";
export const RECORDS_FINISHED = "RECORDS_FINISHED";
export const RECORDS_SUCCESS = "RECORDS_SUCCESS";
export const SET_PAGINATION = "SET_PAGINATION";
export const SET_FILTERS = "SET_FILTERS";
