export const APPROVE_RECORD = "APPROVE_RECORD";
export const APPROVE_RECORD_STARTED = "APPROVE_RECORD_STARTED";
export const APPROVE_RECORD_SUCCESS = "APPROVE_RECORD_SUCCESS";
export const APPROVE_RECORD_FINISHED = "APPROVE_RECORD_FINISHED";
export const APPROVE_RECORD_FAILURE = "APPROVE_RECORD_FAILURE";
