#! /usr/bin/env bash

services="nginx puma couch_watcher who_watches_the_couch_watcher primero_scheduler backburner beanstalkd solr couchdb"

status () {
  echo "Primero status:"
  systemctl status $services |  awk -F"e:" '/●/ {print $0} ; /Active/ {print "    "$2}'
}

stop () {
  echo "Stopping Primero services"
  systemctl stop $services
  status
  echo "Primero services stopped"
}

start () {
  echo "Starting Primero services"
  systemctl start $services
  status
  echo "Primero services started"
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: primeroctl {start|stop|restart|status}"
    ;;
esac


