#! /bin/bash

seed_script=${1}

source $HOME/.bashrc
cd $HOME/application

bundle exec rake db:data:remove_metadata
bundle exec rake db:migrate:design
bundle exec rails r $seed_script
bundle exec rake couch_changes:prime_sequence_numbers