import NAMESPACE from "./namespace";

export const SET_SELECTED_FORM = `${NAMESPACE}/SET_SELECTED_FORM`;
export const SET_FORMS = `${NAMESPACE}/SET_FORMS`;
export const SELECTED_RECORD = `${NAMESPACE}/SELECTED_RECORD`;
export const SELECTED_RECORD_SUCCESS = `${NAMESPACE}/SELECTED_RECORD_SUCCESS`;
