import NAMESPACE from "./namespace";

export const SET_SELECTED_FORM = `${NAMESPACE}/SET_SELECTED_FORM`;
export const SET_FORMS = `${NAMESPACE}/SET_FORMS`;
export const RECORD_FORMS = `${NAMESPACE}/RECORD_FORMS`;
export const RECORD_FORMS_STARTED = `${NAMESPACE}/RECORD_FORMS_STARTED`;
export const RECORD_FORMS_SUCCESS = `${NAMESPACE}/RECORD_FORMS_SUCCESS`;
export const RECORD_FORMS_FINISHED = `${NAMESPACE}/RECORD_FORMS_FINISHED`;
export const RECORD_FORMS_FAILURE = `${NAMESPACE}/RECORD_FORMS_FAILURE`;
export const SET_OPTIONS = `${NAMESPACE}/SET_OPTIONS`;
